lib/pages/explore/explore_page.dart
pubspec.lock

@Feichtmeier I can't push branch on this project, it is normal?

Remove deleted carousel margin property

---

lib/pages/explore/app_dialog.dart
lib/pages/explore/app_grid.dart
lib/pages/explore/explore_page.dart
lib/pages/my_apps/my_apps_page.dart
lib/pages/updates/updates_page.dart

https://api.flutter.dev/flutter/widgets/State/initState.html
> Implementations of this method should start with a call to the inherited method, as in super.initState().

Call super.initState() first

---

lib/pages/explore/app_dialog.dart

AppDialog: use new carousel controls

---

lib/main.dart
lib/pages/common/snap_model.dart
lib/pages/explore/app_banner.dart
lib/pages/explore/explore_page.dart
lib/services/color_generator.dart
lib/snapx.dart
pubspec.lock
pubspec.yaml

Add (Dominant)ColorGenerator for surface tint colors

---

pubspec.lock

- currently advantage is to profit of the new and working light/dark theme detection in the master channel

Use flutter master for development

---

lib/main.dart
lib/services/app_change_service.dart
pubspec.lock
pubspec.yaml

https://user-images.githubusercontent.com/15329494/173187345-75fa7f96-6c46-492b-8360-6da86b2f5a2b.mp4
Question but not urgent for merge:
@3v1n0 any tip how I can create this nice "busy" flipping of the app Icon with the notify api ? :)

Add desktop notifcation when snap change is ready

---

lib/store_app/common/snap_content.dart
lib/store_app/common/snap_dialog.dart
lib/store_app/common/snap_model.dart
lib/store_app/common/snap_page_header.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/filter_bar.dart
lib/store_app/explore/search_field.dart

https://user-images.githubusercontent.com/15329494/173226303-3df18a51-2bc4-40d8-a717-6126faf91e31.mp4

Detangle UI components a bit more

---

lib/l10n/app_en.arb
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_field.dart
lib/store_app/explore/section_banner_grid.dart
linux/my_application.cc

https://user-images.githubusercontent.com/15329494/174498400-0e77f072-d590-4bb8-b5a2-4c0e70f63b8f.mp4

Improve search UI

---

README.md
lib/l10n/app_en.arb
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_field.dart
lib/store_app/explore/search_page.dart
lib/store_app/my_apps/my_apps_page.dart

https://user-images.githubusercontent.com/15329494/174582610-8be4ed47-ab96-4134-8ebf-3ecee0624a53.mp4

Add packagekit package search

---

lib/package_installer/package_installer_model.dart
lib/store_app/my_apps/my_packages_model.dart
lib/store_app/my_apps/package_dialog.dart
lib/store_app/my_apps/package_model.dart
lib/store_app/my_apps/system_updates_model.dart
lib/store_app/my_apps/system_updates_page.dart
linux/my_application.cc

- clear updates before refresh
- add feature to add repos
- connect in model constructors to be safe

PackageKit improvements

---

lib/store_app/explore/explore_page.dart
lib/store_app/store_app.dart

ExplorePage: move offline logic to builder

---

lib/store_app/common/app_banner.dart

Flatten AppBanners to fit to Yaru Design

---

lib/l10n/app_en.arb
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/store_app.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Move updates to main navigation

---

lib/store_app/updates/updates_page.dart

updatespage: improve chechboxes

---

lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
pubspec.lock

Improve UpdatesPage

---

lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/snap_banner_carousel.dart

https://user-images.githubusercontent.com/15329494/181900534-bb4b7e17-2b2c-425e-baa2-6eae7c7c2f34.mp4
Fixes #71

ExplorePage: make everything scroll with input

---

lib/l10n/app_en.arb
lib/l10n/app_fr.arb
lib/store_app/updates/update_banner.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Updates: add reboot button and simplify padding

---

lib/store_app/common/snap_section.dart
pubspec.lock

Change the "All apps" icon

---

lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart
lib/store_app/explore/search_page.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/updates/update_banner.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
pubspec.lock

https://user-images.githubusercontent.com/15329494/183880537-5796f5d7-3fce-4a47-957c-9e3484b3f84c.mp4
@madsrh this changes only the gridview to a listview plus some padding depending on screenwidth. Other changes can be done in a different PR - is this okay for you like this? 
Ref #81

UpdatePage: change from Grid to ListView with adaptive padding

---

lib/l10n/app_en.arb
lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart
pubspec.lock
pubspec.yaml

UpdatesPage: show changelog in dialog

---

lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart
pubspec.lock
pubspec.yaml

Updates: improve dialog padding and use markdown

---

lib/l10n/app_en.arb
lib/store_app/common/constants.dart
lib/store_app/updates/update_banner.dart
lib/store_app/updates/updates_page.dart
pubspec.lock

UpdatesPage: make the ok icon green, add padding

---

lib/store_app/common/animated_scroll_view_item.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/updates/updates_page.dart
pubspec.lock

Thanks to @Roaa94 for the code!
https://user-images.githubusercontent.com/15329494/185741198-61902168-2c10-419a-8e51-204f9b17d9b4.mp4

Animate items in the ScrollViews

---

lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart

this need in this tabbed view because horizontal and vertical scrolling conflict otherwise

MyApps Tabs: create additional ScrollControllers

---

lib/store_app/updates/updates_page.dart
pubspec.lock

[Capture vidéo du 23-08-2022 13:45:54.webm](https://user-images.githubusercontent.com/36476595/186149990-7be913f8-d269-4f59-9cdb-92b975f0391e.webm)
**Note:** the capture is lagging, but it works well :)
Closes #87

Use YaruAnimatedOkIcon

---

lib/store_app/updates/update_banner.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
pubspec.lock

https://user-images.githubusercontent.com/15329494/186660984-24ae26c7-1f56-4a98-bfd1-965be68e724b.mp4
Fixes #95
Fixes #76

UpdatePage: fix progress indicators

---

lib/store_app/store_model.dart
pubspec.lock

https://user-images.githubusercontent.com/15329494/186666369-e6221f9b-2344-40b5-b093-d32f0c7e1066.mp4
Fixes #97

ExplorePage: prevent offline page to show up too early

---

lib/store_app/my_apps/my_packages_model.dart

MyApps>Debs: only show GUI applications

---

lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Add a check for updates splash screen

---

lib/main.dart
lib/services/package_service.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
lib/updates_state.dart

https://user-images.githubusercontent.com/15329494/186964180-9aab83c7-6af7-4220-ba54-34d10f0550ef.mp4
https://user-images.githubusercontent.com/15329494/186964220-cbd0326f-fe0a-48d0-9931-7086f251e1df.mp4
Closes #78

Move update logic to service

---

lib/main.dart
lib/services/package_service.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.lock
pubspec.yaml

https://user-images.githubusercontent.com/15329494/186981331-c879077c-463d-41bf-9375-0defb2ce2f9e.mp4
Thanks @jpnurmi for the idea
Fixes #106

PackageService: prevent app from closing if refreshing or updating

---

lib/package_state.dart
lib/services/package_service.dart
lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart
lib/store_app/common/utils.dart
lib/store_app/my_apps/my_packages_model.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/updates/updates_model.dart
pubspec.lock

PackageService: use in all packagekit models

---

lib/services/package_service.dart

Use window managet set closable in a finally block

---

lib/l10n/app_en.arb
lib/store_app/store_app.dart
lib/store_app/updates/updates_page.dart

- show text on all buttons
- smaller badges
- fully opaque badges

Updates + MyAppsPage: design improvements

---

lib/store_app/common/snap_dialog.dart
pubspec.lock

https://user-images.githubusercontent.com/15329494/187248046-40eaaf90-86c6-46e8-8f29-23b6b10eff2a.mp4
Fixes #99

Dialog with app details cannot be closed with a mouse when scrolled down

---

lib/store_app/common/snap_model.dart

SnapDialog: localize timestamps.

---

lib/store_app/common/snap_channel_expandable.dart
lib/store_app/common/snap_dialog.dart
lib/store_app/common/snap_model.dart

Also add back a timestamp tooltip for the "Last Updated" field.
Ref: #134.

SnapDialog: use localized timestamps for the tooltips.

---

lib/package_installer/package_installer_app.dart
lib/package_installer/package_installer_model.dart
lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart
lib/store_app/my_apps/my_packages_model.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Models: inject service from view to model

---

lib/store_app/updates/updates_page.dart
pubspec.lock

|Before|After|
|-|-|
|![grafik](https://user-images.githubusercontent.com/15329494/187855074-c3d497b5-aa17-4135-99ee-ffcf29222576.png)|![grafik](https://user-images.githubusercontent.com/15329494/187854956-2bc2647e-b50c-44d6-aea8-87487d7fb85d.png)|
Fixes #147

UpdatesPage: prevent overflow of controls for long labels (for example german...)

---

lib/store_app/updates/updates_page.dart

UpdatesPage: always place controls at the right

---

lib/services/package_service.dart
lib/store_app/my_apps/my_packages_model.dart
lib/store_app/my_apps/my_packages_page.dart

MyPackages: do not display all installed by default

---

lib/services/package_service.dart
lib/store_app/common/package_dialog.dart
lib/store_app/common/package_model.dart

@alculete 
the dialogs will be merged to one layout in the future (so the packagekit dialog looks as fancy as the snap dialog... currently we do not have images yet as #128 needs to happen) , but this should fix the issue for now :)  
Fixes #153

Show progress of packagekit installations/uninstallations

---

lib/store_app/common/offline_page.dart
lib/store_app/common/package_dialog.dart
lib/store_app/common/snap_page_header.dart
lib/store_app/updates/updates_page.dart

Fix Flutter 3.1 deprecations

---

pubspec.lock
pubspec.yaml

Move flutter_lints in dev_dependencies

---

lib/store_app/settings/settings_page.dart

Wire up clicking hyperlinks in the about dialog.

---

lib/store_app/updates/updates_page.dart

UpdatePage: align header to the right

---

assets/contributors.md

Is this okay for you @oyajun?
Fixes #186

Display translators name in this app

---

lib/store_app/explore/search_field.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.lock
pubspec.yaml

Use Yaru 0.4

---

snap/snapcraft.yaml

The rendering issues are fixed in 3.3.2 and we need the theme sync fixed after 3.0
https://groups.google.com/g/flutter-announce/c/YGf90mszrAw/m/7q1a3UmrBgAJ
Fixes #189

Snap: return to flutter source-branch stable

---

lib/package_installer/package_installer_app.dart
lib/store_app/store_app.dart
pubspec.lock
pubspec.yaml

Wide Layout part 1: navigation
https://user-images.githubusercontent.com/15329494/190861115-46d7b3d4-fbb0-4e75-864e-56508f9b13ba.mp4
Ref #226

SoftwareApp: adapt navigation to screen width

---

lib/services/package_service.dart

UpdatePage: improve update count visualization

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/services/package_service.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Updates: create notification when complete

---

lib/store_app/common/app_header.dart
lib/store_app/common/border_container.dart
lib/store_app/common/package_controls.dart
lib/store_app/common/package_model.dart
lib/store_app/common/package_page.dart
lib/store_app/common/page_layouts.dart
lib/store_app/common/snap_page.dart

[Bildschirmaufzeichnung vom 21.09.2022, 11:08:32.webm](https://user-images.githubusercontent.com/15329494/191482196-e1fe27ea-1954-4065-8c51-036bd076105e.webm)

AppPages: improve window width adaption

---

lib/store_app/common/app_data.dart
lib/store_app/common/app_header.dart
lib/store_app/common/app_infos.dart
lib/store_app/common/app_page.dart
lib/store_app/common/snap_channel_button.dart
lib/store_app/common/snap_channel_infos.dart
lib/store_app/common/snap_controls.dart
lib/store_app/common/snap_page.dart

Improve channel selection and presentation 

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/settings/settings_model.dart
lib/store_app/settings/settings_page.dart

Provide a link to project's github page

---

lib/store_app/common/app_icon.dart
lib/store_app/common/dialogs/app_dialog_content.dart
lib/store_app/common/dialogs/package_dialog.dart
lib/store_app/common/dialogs/snap_dialog.dart
lib/store_app/common/media_tile.dart
lib/store_app/common/safe_network_image.dart

Import YaruSafeImage as SafeNetworkImage

---

lib/store_app/common/snap_channel_button.dart

Ref https://github.com/ubuntu-flutter-community/software/issues/260#issuecomment-1256090347

SnapChannelButton: improve dropdown

---

lib/store_app/common/app_page.dart
lib/store_app/common/media_tile.dart

@madsrh wanted a carousel within a carousel and I almost created a never ending recursion :D 
But he is right so here it is. Is this good
[Bildschirmaufzeichnung vom 25.09.2022, 11:46:03.webm](https://user-images.githubusercontent.com/15329494/192137543-8540ce10-9c0e-4d54-a644-a1fe70500f61.webm)
@madsrh ?

AppMedia: create a fullscreen carousel on tap

---

lib/store_app/common/app_infos.dart

AppInfo: use wrap instead of row

---

lib/l10n/app_ru.arb

Update russian translation

---

lib/services/package_service.dart
pubspec.lock
pubspec.yaml

PackageService: cancel previous search if still ongoing

---

lib/store_app/common/dialogs/snap_dialog.dart
lib/store_app/common/snap_controls.dart
lib/store_app/common/snap_model.dart

- SnapModel: add more comments and re-order the file
- SnapControls: disable refresh button if the selected channel has no update

SnapModel and controls improvements

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/explore/search_field.dart

- better SnapSection.all english and german strings
- ESC with empty input but changed filter will return to all
- add a clear input button
Ref ExplorePage: add categories to frontpage #301
[yayaya.webm](https://user-images.githubusercontent.com/15329494/192830087-51c26813-e112-4014-8b16-91ef5625c8e8.webm)

Search improvements

---

lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/snap_banner_carousel.dart
lib/store_app/explore/start_page.dart

[okok.webm](https://user-images.githubusercontent.com/15329494/192882343-78ac62b0-2b32-41b0-bea0-51e35979d306.webm)
CC @madsrh @anasereijo 
Fixes #301

ExplorePage: add categories to frontpage

---

lib/services/snap_service.dart
lib/store_app/common/snap_connections_settings.dart
lib/store_app/common/snap_model.dart
lib/store_app/common/snap_page.dart
pubspec.lock
pubspec.yaml

SnapModel: toggle connections correctly

---

lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/my_apps/my_apps_search_field.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart

[Bildschirmaufzeichnung vom 29.09.2022, 15:33:33.webm](https://user-images.githubusercontent.com/15329494/193045801-95827dae-5cb9-4ebb-9eda-5abcee08f52a.webm)
Fixes #167

Add search option on installed applications

---

lib/store_app/common/app_page.dart
lib/store_app/common/page_layouts.dart
lib/store_app/common/snap_page.dart

Tweak responsive layout for app page

---

README.md

Fix: #145 
Made it similar to the one in [Settings README.md](https://github.com/ubuntu-flutter-community/settings/blob/master/README.md) file

Added to README.md flutter install instructions for snap (#145)

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/explore/explore_model.dart
lib/store_app/explore/search_page.dart

Packagekit not ready
Searching
no package found
no snap found
These are only placeholders until we have icons and/or design for this
CC @Jupi007 @anasereijo @madsrh

Search result improvements:

---

lib/store_app/explore/search_page.dart

Continue from #333 
A little more cuteness until we have something better :smile:

Search result page improvements

---

lib/store_app/explore/search_field.dart

Fix category selector overflow

---

lib/main.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
pubspec.lock
pubspec.yaml

Fixes #266
@d-loose could you add a similar method for logout?

Make restart button work in the snap

---

lib/services/package_service.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

Send a notification if new updates are available

---

lib/store_app/explore/explore_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/start_page.dart
lib/store_app/my_apps/my_snaps_page.dart

@madsrh  is this good?
[infinity_war.webm](https://user-images.githubusercontent.com/15329494/193816482-7e4c2816-1c7a-434e-8621-dcfb9a36d647.webm)
Fixes #289

Add infinite scrolling when exploring apps

---

lib/package_installer/package_installer_app.dart
lib/store_app/common/app_page.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/snap_banner_carousel.dart
lib/store_app/explore/start_page.dart
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/settings/settings_page.dart
lib/store_app/store_app.dart
lib/store_app/updates/update_banner.dart
lib/store_app/updates/update_dialog.dart
lib/store_app/updates/updates_page.dart
pubspec.lock
pubspec.yaml

Everything works as before but better :) 
[ya12.webm](https://user-images.githubusercontent.com/15329494/194380532-e3e20e85-1559-4419-97a1-7401cacc7479.webm)
[sdfsdf.webm](https://user-images.githubusercontent.com/15329494/194380539-81e65503-11aa-4b57-b8c8-9df64ae25133.webm)
Closes #181

Sync banners, carousel and compactlayout

---

CONTRIBUTING.md

Add a section for translations (referencing Weblate) in the CONTRIBUTING.md document.

---

lib/store_app/explore/start_page.dart

Frontpage categories should be clickable

---

lib/store_app/updates/update_dialog.dart

| |Before|After|
|-|-|-|
|Light|![grafik](https://user-images.githubusercontent.com/15329494/195064313-a5735770-7e29-452a-9a46-4f7b12087d22.png)|![grafik](https://user-images.githubusercontent.com/15329494/195063990-1446b4d5-a544-4ba1-becc-f064de64dcfb.png)|
|Dark|![grafik](https://user-images.githubusercontent.com/15329494/195064404-a2b67e88-2801-4fa1-a8be-b8450eb296f4.png)|![grafik](https://user-images.githubusercontent.com/15329494/195064086-e38d6da2-8e76-43d6-bc7f-9bc7ff933a6a.png)|
Fixes #382

UpdateDialog: improve changelog and presentation

---

lib/store_app/store_model.dart

@d-loose could you test it with your connections?
Fixes #361

StoreModel: allow all types of networks to count as online

---

.github/workflows/cla-check.yaml

Skip the CLA check for pull requests opened by Weblate (translations).

---

lib/store_app/common/drop_down_decoration.dart

DropDownDecoration: move arrows to the right

---

analysis_options.yaml
lib/services/package_service.dart

Ensure transaction event stream subscriptions aren't leaked.

---

lib/services/package_service.dart
test/services/package_service_test.dart

Correctly emit isInstalled events when a package is installed/removed.

---

lib/store_app/common/app_format_popup.dart
lib/store_app/common/packagekit/packagekit_filter_button.dart
lib/store_app/common/packagekit/packagekit_group_button.dart
lib/store_app/common/snap/snap_channel_button.dart
lib/store_app/common/snap/snap_section_popup.dart
lib/store_app/common/snap/snap_sort_popup.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/search_page.dart
pubspec.yaml

PackageKitFilter: dropdown is now multi select
as PackageKitFilter is a Set, let the dropdown be multi-select

Packagekitfilter: use multifilter popup

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/common/multi_select_item.dart
lib/store_app/common/packagekit/packagekit_filter_button.dart
lib/store_app/updates/update_dialog.dart
pubspec.yaml

UpdateDialog: give changelog more space

---

lib/store_app/common/app_page/page_layouts.dart

https://user-images.githubusercontent.com/15329494/197384077-6f3bbfc5-0fcc-4b90-99ab-160a1b5de62c.mp4

LageLayouts: do not scale vPadding

---

lib/package_installer/wizard_page.dart
lib/store_app/common/app_page/app_infos.dart
lib/store_app/common/app_page/page_layouts.dart
lib/store_app/common/constants.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/my_apps/my_apps_header.dart
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/updates/update_banner.dart
lib/store_app/updates/updates_page.dart

- add more constants to constants.dart for padding
- change green constant names
- use them in grids
- make wizard page constants private so they do not show up in code completion
no visual changes

unify constants and padding

---

lib/store_app/common/app_page/app_description.dart
lib/store_app/common/app_page/app_page.dart
pubspec.yaml

AppPage: fix scrolling issues

---

lib/store_app/updates/update_dialog.dart

[ya.webm](https://user-images.githubusercontent.com/15329494/197771502-0b9cec82-1727-44fb-a41a-91a36ec48213.webm)

UpdateDialog: fix padding and scrolling

---

lib/store_app/common/app_page/app_page.dart
lib/store_app/common/app_page/page_layouts.dart

https://user-images.githubusercontent.com/15329494/197777019-bc361bf7-0b41-4750-ac6d-10d588bc5e05.mp4

AppPage and Layouts: left align and reduce padding

---

lib/store_app/common/app_page/app_page.dart

https://user-images.githubusercontent.com/15329494/197780781-8fcf8ae9-52dc-48ab-aaa5-8d7d7b6e6bb4.mp4
Ref #224

Add keyboard listener for navigating in app dialog media carousel

---

lib/store_app/explore/explore_header.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/search_page.dart

https://user-images.githubusercontent.com/15329494/198088983-4da46cfc-9d4e-41dc-88bf-539d1a7fa6bf.mp4
Ref #319

Combine search results

---

lib/store_app/explore/search_page.dart

_CombinedSearchPage: show summary if available

---

.github/workflows/analyze.yml
.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/test.yml
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/services/package_service.dart
lib/store_app/common/message_bar.dart
lib/store_app/settings/repo_dialog.dart
lib/store_app/settings/settings_page.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart

- display errors in a snackbar
- move the repo dialog to the settings page
- small improvements to the about dialog and settings page
- fix repo toggling to update the repo dialog
https://user-images.githubusercontent.com/15329494/198711289-c99d1cb4-a24a-4bc5-9786-5053e82258ed.mp4
https://user-images.githubusercontent.com/15329494/198717923-87b71f3a-d58d-4a51-ab3f-b90778ca6ee2.mp4

Update Settings and error Display

---

lib/store_app/common/app_page/app_page.dart
lib/store_app/common/snap/snap_page.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/settings/settings_page.dart
lib/store_app/store_app.dart
lib/store_app/updates/updates_page.dart

Always call super.initState first

---

CONTRIBUTING.md
lib/services/package_service.dart
lib/store_app/common/packagekit/packagekit_filter_button.dart
lib/store_app/my_apps/my_apps_header.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_packages_page.dart
test/services/package_model_test.mocks.dart
test/services/package_service_test.dart
test/widget_test.mocks.dart

https://user-images.githubusercontent.com/15329494/198838992-7a639e15-fdb6-40f5-82f0-4466e4d50abc.mp4
Fixes #157

Add a toggle to hide/show deb libraries and plugins

---

lib/main.dart
lib/store_app/settings/settings_model.dart
lib/store_app/settings/settings_page.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart

https://user-images.githubusercontent.com/15329494/198978908-50ca04b1-5051-4e4e-b05f-b09738328451.mp4
Fixes #453

remove the hide on close trick made with windowmanager

---

lib/main.dart
lib/store_app/store_model.dart

PackageInstaller: allow closing

---

lib/store_app/common/packagekit/package_model.dart

Fix local package installation by looking at the local path first.

---

lib/store_app/common/app_data.dart
lib/store_app/common/app_page/app_header.dart
lib/store_app/common/app_website.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/common/snap/snap_model.dart
lib/store_app/common/snap/snap_page.dart
lib/store_app/explore/color_banner.dart

Support star developer in the Snap Store

---

lib/store_app/explore/search_page.dart

https://user-images.githubusercontent.com/15329494/199422593-b36221c4-7189-477f-b5e2-20b5a56cac05.mp4
Thanks for the idea https://github.com/AaronTechnic

SearchPage: ask for AppFormat before push

---

lib/store_app/common/app_data.dart
lib/store_app/common/app_page/app_header.dart
lib/store_app/common/app_page/app_page.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/common/snap/snap_page.dart

AppPage: app titles shouldn't be super long

---

lib/store_app/common/app_page/app_page.dart

Align text + icon when switching "page"

---

lib/store_app/updates/updates_page.dart

UpdatesPage: adapt to long translations

---

lib/main.dart
lib/services/package_service.dart

remove update check timer in packageService

---

lib/store_app/common/app_page/app_header.dart

thanks to @mivoligo =)
https://user-images.githubusercontent.com/15329494/200368996-398268c9-8d35-4cde-b88e-ac20a71fbb6a.mp4

AppHeader: fit the title with FittedBox

---

lib/store_app/explore/explore_model.dart

instead of first replacing then putting it again, let's use the update method rather

ExploreModel: update AppFinding

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/services/snap_service.dart
lib/store_app/common/snap/snap_controls.dart
lib/store_app/common/snap/snap_model.dart

SnapPage: show what change is in progress

---

lib/l10n/app_en.arb
lib/store_app/updates/updates_page.dart

L10n add text line for refresh button on the updates page

---

lib/store_app/common/app_data.dart
lib/store_app/common/app_page/app_header.dart
lib/store_app/common/app_page/app_infos.dart
lib/store_app/common/app_page/app_reviews.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/common/snap/snap_channel_button.dart
lib/store_app/common/snap/snap_model.dart

- re-add install date
- re organize app infos to be more flexible and reacting on space available
- color snap channel button green if the version has been changed by the user
- add stars to the app headers
Closes #237

AppPage refinements

---

lib/store_app/common/app_page/app_loading_page.dart
lib/store_app/common/snap/snap_page.dart
pubspec.yaml

https://user-images.githubusercontent.com/15329494/202524552-0809325d-4ffa-4d65-89d4-3d904edd20b0.mp4
https://user-images.githubusercontent.com/15329494/202526447-7668194e-cc3d-4c2d-845e-5ddf04c70aa7.mp4
Ref #344

Use shimmer effect for loading content

---

lib/store_app/explore/section_banner.dart

[Bildschirmaufzeichnung vom 18.11.2022, 09:17:22.webm](https://user-images.githubusercontent.com/15329494/202654461-dacb38d8-5fe9-437a-af48-ce58aa337fee.webm)

SectionBanner: change icon shadow on hover

---

lib/store_app/common/app_page/app_loading_page.dart
lib/store_app/common/app_page/app_page.dart

https://user-images.githubusercontent.com/15329494/202690873-52b359f8-9fe6-444a-a5dd-0f3b3b98ed61.mp4
Ref #259

AppPage: add two finger swipe gesture to navigate back

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/common/app_data.dart
lib/store_app/common/app_model.dart
lib/store_app/common/app_page/app_header.dart
lib/store_app/common/app_page/app_page.dart
lib/store_app/common/app_page/app_reviews.dart
lib/store_app/common/packagekit/package_model.dart
lib/store_app/common/snap/snap_model.dart
lib/store_app/common/snap/snap_page.dart

- move all reviews to a dialogue for details
- move the control buttons under the carousel

Review improvements

---

lib/store_app/common/app_page/app_reviews.dart

CC @Jupi007 if have time some time, maybe we can get thin yaru icons for the flag and those regular arrows with quil

AppReviews: replace arrow font with real icons

---

lib/store_app/updates/updates_page.dart

Switch text on updating page

---

lib/store_app/store_app.dart

**Before:**
https://user-images.githubusercontent.com/36476595/203857862-815b9eb5-d1a2-4b11-9552-1d901d6a7701.mp4
**After:**
https://user-images.githubusercontent.com/36476595/203857877-5f48e70d-438e-4b9f-8550-5ecc80c4acfa.mp4
Fixes #565

Avoid confirm dialog to be open multiple times

---

lib/store_app/common/app_format_popup.dart
lib/store_app/explore/explore_header.dart
lib/store_app/explore/explore_model.dart

Explorepage: selecting no package format gives error

---

pubspec.yaml

Pubspec: bump yaru deps

---

lib/store_app/common/app_page/app_loading_page.dart
lib/store_app/common/app_page/app_page.dart
lib/store_app/common/app_page/app_swipe_gesture.dart
lib/store_app/common/constants.dart

Fixes #259 
https://user-images.githubusercontent.com/73116038/204101612-3e812d82-f7fb-4d93-a68b-f767dd262462.mp4
Don't mind the flickering, that's an issue I'll report in a bit :sweat_smile:

One-to-one swipe back gesture for Apps page

---

lib/services/snap_service.dart
lib/store_app/common/snap/snap_model.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
lib/store_app/store_splash_screen.dart
test/services/snap_service_test.dart
test/widget_test.dart

https://user-images.githubusercontent.com/15329494/204362114-34107c7d-dacf-4438-b130-2061f0c4b205.mp4
Fixes #575

ExploreModel: move section map to service and add splash screen

---

lib/store_app/common/snap/snap_sort.dart
lib/store_app/common/snap/snap_sort_popup.dart
lib/store_app/explore/explore_model.dart
lib/store_app/my_apps/my_apps_header.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_snaps_page.dart

- add a snap sort popup if the appformat is snap
- add sort by name, size and installdate
- add a toggle button to show snaps with updates available
https://user-images.githubusercontent.com/15329494/204555589-762df4cf-6e54-4f94-968b-f62a37cac115.mp4

MySnaps: add sort dropdown and update available toggle button

---

lib/appstream_utils.dart
lib/l10n/app_en.arb
lib/main.dart
lib/services/appstream_service.dart
lib/services/package_service.dart
lib/store_app/common/packagekit/package_model.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_page.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
pubspec.yaml
test/appstream_utils_test.dart
test/services/appstream_service_test.dart
test/services/package_service_test.dart
test/widget_test.dart

Appstream service to expose metadata and search for packages.

---

lib/services/snap_service.dart
lib/store_app/my_apps/my_apps_header.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/updates/no_updates_page.dart
lib/store_app/updates/updates_page.dart

https://user-images.githubusercontent.com/15329494/204821892-34c1e40b-2890-4466-b573-2a944a027876.mp4

Improve my_snaps update checking

---

lib/services/snap_service.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_page.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
test/widget_test.dart

- Do not await service init in the explore page
- show the app asap and do not show a splash screen
-  Also use a stream to update explore page and friends
This was taking too long.
Ref #582

Do not await service init in the explore page

---

lib/services/package_service.dart
lib/store_app/store_app.dart
lib/store_app/store_model.dart
lib/store_app/store_splash_screen.dart
lib/store_app/updates/updates_page.dart

- No Auto updates refresh on start-up
- do not wait for services directly in main
- greatly improve start-up time and elimate lags
Also
Fixes #369

Speed up start-up

---

lib/store_app/common/app_icon.dart
lib/store_app/explore/start_page.dart

https://user-images.githubusercontent.com/15329494/205283381-bdfd4d97-9b22-4431-b7eb-2e519eebb873.mp4
Closes #344

Add shimmer effect to StartPage and AppIcon

---

lib/store_app/common/indeterminate_circular_progress_icon.dart
lib/store_app/store_app.dart

**Before:**
**After:**
Fixes #590

Fix Navigation Rail circular progress size

---

lib/store_app/my_apps/my_apps_model.dart

With this change, my apps page updates works.
Fixes #594

MyAppsModel: replace null check by null aware

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/common/snap/snap_channel_button.dart

SnapChannelButton: adapt to design

---

lib/store_app/common/updates_splash_screen.dart
lib/store_app/my_apps/my_apps_header.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/updates/updates_page.dart

- wait for authorization
- re-use the updates splash screen with the snapcraft icon
- prepare for migration to updates page (snap tab)
https://user-images.githubusercontent.com/15329494/205434726-647e9dd9-a166-408d-8515-99275c07f298.mp4

Improve MySnaps updating

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/installed/installed_header.dart
lib/store_app/installed/installed_model.dart
lib/store_app/installed/installed_packages_page.dart
lib/store_app/installed/installed_page.dart
lib/store_app/installed/installed_search_field.dart
lib/store_app/installed/installed_snaps_page.dart
lib/store_app/store_app.dart

Rename MyApps and friends to Installed and friends
Fixes #604

Rename MyApps and friends to Installed and friends

---

lib/store_app/common/app_icon.dart
lib/store_app/common/app_page/app_loading_page.dart
lib/store_app/common/app_page/app_page.dart
lib/store_app/common/border_container.dart
lib/store_app/common/constants.dart
lib/store_app/common/loading_banner_grid.dart
lib/store_app/common/snap/snap_grid.dart
lib/store_app/explore/color_banner.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner.dart
lib/store_app/explore/section_grid.dart
lib/store_app/installed/installed_packages_page.dart
lib/store_app/store_app.dart
pubspec.yaml

~~@jpnurmi managed to get everything back like it was except there is a weird thing, when switching themes, the banners remain in the old color~~

Update banners, navigation and colors to new yaru widgets

---

lib/store_app/explore/start_page.dart

StartPage: use select() to optimize rebuilds

---

lib/store_app/explore/explore_model.dart
pubspec.yaml

Fix: Search cannot find any packages in 22.10

---

lib/app/common/snap/snap_channel_button.dart
lib/app/common/snap/snap_model.dart

Add divider in channel list

---

lib/l10n/app_en.arb

Rename package format dropdown

---

lib/app/app.dart
lib/main.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
linux/my_application.cc
pubspec.yaml
test/widget_test.dart

Handles CLI arguments in the running application and updates the UI accordingly.
https://user-images.githubusercontent.com/113362648/207024663-bcb953b7-12fd-4bd3-96b2-cdfddda4a22a.mp4
(sorry for the long loading times in the recording, picking large packages like firefox and thunderbird probably wasn't the best choice)

Use GtkApplicationNotifier to handle CLI arguments

---

lib/app/app.dart
lib/app/app_model.dart
lib/app/common/close_confirmation_dialog.dart
lib/app/common/constants.dart
lib/app/common/page_item.dart
lib/app/explore/explore_page.dart
lib/app/installed/installed_page.dart
lib/app/package_installer/package_installer_page.dart
lib/app/settings/repo_dialog.dart
lib/app/settings/settings_page.dart
lib/app/updates/package_updates_model.dart
lib/app/updates/package_updates_page.dart
lib/app/updates/updates_page.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/services/packagekit/package_service.dart

- make sources dialog work again
- make use of the tab index of the updates page and not the installed page, which has no tabbed view anymore since quite some time...
- clean up app.dart and move builders pageitem to the corresponding pages
- add a description to settings page source tile

Clean up app.dart and settingspage

---

lib/app/common/app_banner.dart
lib/app/common/constants.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_grid.dart
lib/app/common/snap/snap_page.dart
lib/app/explore/explore_model.dart
lib/app/explore/search_page.dart
lib/app/explore/section_banner.dart
lib/app/explore/section_grid.dart

Add an option to return to the other packageformat if it exists from the Snap/Packagepage

---

lib/app/common/app_banner.dart
lib/app/common/constants.dart
lib/app/explore/explore_model.dart
lib/snapx.dart

Closes #642 
Ref https://github.com/ubuntu-flutter-community/software/discussions/634

Adapt search banners to design

---

lib/app/common/app_banner.dart
lib/app/common/app_finding.dart
lib/app/common/snap/snap_grid.dart
lib/app/explore/explore_model.dart
lib/app/explore/search_page.dart
lib/app/explore/section_grid.dart

Ref https://github.com/ubuntu-flutter-community/software/discussions/634

ExplorePage + InstalledSnapsPage: use new banners

---

lib/app/common/app_banner.dart
lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/constants.dart

AppBanners and stars: better colors and sizes

---

lib/app/common/search_field.dart

Currently, only double tapping the text in the textfield selects all of the text. This pr adds the functionality of double tapping anywhere in the textfield to select all of the text.
I think this is more in line with what the average user would expect. :D
https://user-images.githubusercontent.com/73116038/208345871-98c2979f-4bd3-4e7c-a4b2-12f4ead793a2.mp4

Add double tap anywhere in textfield to select all the text

---

lib/app/explore/explore_model.dart

See https://github.com/ubuntu-flutter-community/software/issues/663

Unselect debian packages at start

---

lib/app/common/packagekit/package_controls.dart
lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/services/packagekit/package_service.dart

PackageInstaller: include version matching when checking if the package is installed

---

lib/app/common/snap/snap_utils.dart
lib/app/installed/installed_header.dart
lib/app/installed/installed_model.dart
lib/app/installed/installed_snaps_page.dart
lib/app/updates/snap_updates_model.dart
lib/app/updates/snap_updates_page.dart
lib/services/snap_service.dart
test/services/snap_service_test.dart

Super evil PR with number 666! :smiling_imp: :laughing: 
https://user-images.githubusercontent.com/15329494/208900956-5417dc83-89a1-48e5-b503-a7136fb924ed.mp4
- move sort function to utils
- do not set local snaps on every build, after first start this makes the page a lot faster
- decouple snaps with updates from local snaps in all pages
Oh and I think
Fixes #631

Installed snaps and snap updates: organize

---

lib/app/updates/snap_updates_model.dart
lib/app/updates/snap_updates_page.dart
lib/services/snap_service.dart

https://user-images.githubusercontent.com/15329494/208907799-98f7a59c-d65a-4f6e-8d2b-3a52ac17cf05.mp4

Show "snap has running apps" error in UI

---

lib/app/common/app_banner.dart
lib/app/common/constants.dart

Add star developer icon for app banners

---

lib/app/installed/installed_model.dart

restore notifyListeners call in snapChanges listener

---

.github/workflows/test.yml
integration_test/software_test.dart

~~WIP~~
* use `pumpAndSettle` to wait until the UI is ready
* tap install button
* wait until uninstall button is present and enabled
* tap uninstall button
* wait until uninstall button is gone
* use `en_US.UTF-8` locale to avoid problems in the CI
fix #627

fix integration test

---

lib/app/common/app_page/app_format_toggle_buttons.dart
lib/app/common/app_page/app_header.dart
lib/app/common/packagekit/package_controls.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_channel_button.dart
lib/app/common/snap/snap_controls.dart
lib/app/common/snap/snap_page.dart

https://user-images.githubusercontent.com/15329494/210844030-f2caad0f-853a-4841-a740-562927b9b598.mp4
CC @madsrh @anasereijo 
Ref #561

AppPage: add appformat toggle

---

pubspec.yaml

|---|---|
| ![Screenshot from 2023-01-05 21-06-04](https://user-images.githubusercontent.com/140617/210870522-99ca7883-6daa-422c-9290-b8d869812629.png) | ![Screenshot from 2023-01-05 21-06-43](https://user-images.githubusercontent.com/140617/210870538-540e8ab9-0c67-4f02-a4b0-65da003f838a.png) |

Upgrade handy_window to gain light window border in dark theme

---

lib/app/common/app_page/app_page.dart
lib/app/common/app_page/page_layouts.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart
linux/my_application.cc

- increase default window width
- remove unused callbacks
- remove redundant app format icon
Ref #561

AppFormat toggle button improvements

---

lib/app/common/app_page/app_page.dart
lib/app/common/custom_back_button.dart
lib/app/common/search_field.dart
lib/app/explore/explore_error_page.dart
lib/app/explore/explore_page.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart

ExplorePage: cut into different files

---

lib/app/common/app_page/page_layouts.dart

Slipped through #679 :sweat_smile: 
Before:
After:

Remove extra bottom padding from MyApps page.

---

linux/my_application.cc

Note: when we are better with adaptive layouts we can revert this to 800x600
Ref #688

Prevent weird window sizes

---

lib/app/explore/section_banner.dart

https://user-images.githubusercontent.com/73116038/211159911-80fac00c-6cfb-4c6d-b878-b667c267a4b9.mp4
fixes #703

Add tooltip to banner applications

---

pubspec.yaml

Updated yaru, less strong borders in the dark theme -> less "boxy" look :) CC @anasereijo

Update all the yarus

---

lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_infos.dart
lib/app/common/app_page/info_column.dart
lib/app/common/app_page/publisher_name.dart

Show publisher name on wide and narrow window headers

---

lib/app/explore/start_page.dart

Make initial loading page top padding 20.

---

lib/app/explore/explore_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
pubspec.yaml

https://user-images.githubusercontent.com/113362648/211356768-cf79dd8e-1e16-4229-a431-9b99783c8adf.mp4
close #254

Navigate back by clicking on selected entry in left pane

---

lib/app/common/app_page/app_header.dart
lib/app/common/app_page/publisher_name.dart

long names
short names
Fixes #717

Limit publisher name width

---

lib/app/common/app_page/app_format_toggle_buttons.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart

AppPages: always display information about the AppFormat

---

lib/app/common/app_page/publisher_name.dart

Publisher star icons are too big

---

lib/app/common/packagekit/package_model.dart
lib/services/packagekit/package_service.dart
test/services/package_model_test.dart

Rebased version of #473
.. and this is #743 by complete coincidence :D

Cancel a background updates check when opening the details page for a package.

---

lib/app/explore/section_banner.dart

SectionBanner: wrap inkwel lin material

---

lib/app/common/app_page/app_loading_page.dart
lib/app/common/app_page/app_page.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart

Use the round back button as before

---

lib/app/updates/updates_page.dart

Updatespage: fix tabs width

---

lib/app/explore/section_grid.dart
lib/app/explore/start_page.dart

The start page needs a re-design, this makes it detached from the search and leaves room for different layouts.
Edit: info for the other designers... no visual changes in here... nothing to see here :smile_cat:  :wave:

StartPage: prepare to be more modulare

---

lib/app/explore/search_page.dart

https://user-images.githubusercontent.com/15329494/212175100-cee79025-d105-4bf8-bb32-0c227b7026f1.mp4
Fixes #755

Fix: The selected snap category change does not rebuild the page anymore

---

lib/app/explore/search_page.dart

Improvement of #756 to keep the spirit of #609 alive

Use `context.select` in SearchPage

---

lib/app/common/search_field.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart

Edit: for screenshots please scroll down
Fixes #752

Searchbar look

---

lib/app/app.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/message_bar.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/search_field.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/repo_dialog.dart
lib/app/settings/settings_page.dart
lib/app/updates/update_dialog.dart
lib/app/updates/updates_page.dart
pubspec.yaml

This should update the edge channel in some hours.

Release 0.2.6 to edge

---

lib/app/updates/updates_page.dart

UpdatesPage: improve tab styling

---

lib/app/app.dart
lib/app/updates/updates_page.dart

Bug fix :bug:  :lady_beetle: 
https://user-images.githubusercontent.com/15329494/212534813-098f7dc7-9e72-4439-8678-a9893a1e1a57.mp4
Fixes #779

UpdatesPage: make tab styling work on all window sizes

---

lib/app/updates/updates_page.dart

... for discoverability of system updates

Updates Page: swap tabs

---

lib/app/common/app_banner.dart
lib/app/common/app_page/app_page.dart
lib/app/common/base_plate.dart
lib/app/explore/section_banner.dart

AppIcons: always use a BasePlate?

---

lib/app/common/packagekit/package_page.dart

https://user-images.githubusercontent.com/15329494/212567014-bf1aa0da-312a-4208-9b31-7ef803192c38.mp4
Edit: lol this game is crazy xD and good music!
Fixes #790

PackagePage: dependency dialog should pop after clicking install

---

lib/app/updates/snap_updates_model.dart
lib/app/updates/snap_updates_page.dart

SnapUpdates: replace future builders with init/notify

---

lib/app/updates/updates_page.dart

Updates: create a single page if packagekit is not available

---

lib/app/updates/snap_updates_page.dart

Bug Fix, The grid should not be centred. Regression from #787

SnapUpdates: fix grid to be top aligned

---

test/services/snap_service_test.dart

I'd like to make sure we don't neglect #387 too much :)

update `snap_service` tests

---

lib/app/explore/start_page.dart

Search field becomes unfocused when its contents become empty.

---

lib/app/common/app_banner.dart
lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_page.dart
lib/app/common/base_plate.dart

Removes the baseplate again, as a consensus in #802  , thus not requesting the review again
Fixes #802

Remove the icon baseplate for app banners and app pages

---

test/services/package_service_test.dart

back to a bit more than 20% coverage \o/
Ref #387

improve package service tests

---

lib/app/explore/explore_page.dart

https://user-images.githubusercontent.com/15329494/213257326-b7071789-805f-4d29-8d3f-bd04d5412d1e.mp4
Fixes #816

Bug on title bar when showing connection issue

---

lib/app/common/packagekit/package_controls.dart
lib/app/common/snap/snap_controls.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/771

Exchange all occurences of "refresh" with "update"

---

integration_test/software_test.dart
lib/app/app.dart
lib/app/package_installer/package_installer_page.dart

https://user-images.githubusercontent.com/113362648/213518363-b5344ce1-ec11-4d1c-a106-5412ffe38d9b.mp4
Edit:
To test it locally you either have to build the snap, or install a local .desktop file and set the mime type handler accordingly, e.g.
```bash
$ xdg-mime default software.desktop x-scheme-handler/snap
```
close #303

Handle snap urls

---

lib/app/common/app_page/app_loading_page.dart
lib/app/common/app_page/app_page.dart
lib/app/common/message_bar.dart
lib/app/explore/explore_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart
pubspec.yaml

Before:
https://user-images.githubusercontent.com/15329494/213411638-fcbad16c-57e3-44f0-9896-c0f2044cfb2c.mp4
After:
https://user-images.githubusercontent.com/15329494/213548747-b55a1eb3-de50-4ea7-bd78-de0f8f18e897.mp4

Use YaruDetailPage to limit animation rect

---

lib/app/common/app_page/app_infos/app_size_fragment.dart
lib/app/common/app_page/app_infos/released_at_info_fragment.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/836

Small tooltip fixes

---

lib/app/common/app_page/app_loading_page.dart
lib/app/common/app_page/app_page.dart
lib/app/explore/explore_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart
pubspec.yaml

- update yaru widgets to make sure this bug is not related plus some fixes
- re-replace yarudetailpage with scaffold as a band-aid fix for #835 
Ref #835
https://user-images.githubusercontent.com/15329494/213794611-e8be523b-6d35-4403-b4f3-9d2335e76e78.mp4

Re-replace yarudetailpage with scaffold

---

lib/app/common/app_page/app_infos/publisher_info_fragment.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/839

Change maxWidth to avoid cutoff

---

lib/app/updates/package_updates_page.dart

Regression from #846 
Fixes #857

Re-add padding to deb updates page

---

lib/app/app.dart
lib/app/updates/package_updates_page.dart
lib/app/updates/snap_updates_page.dart
lib/app/updates/updates_model.dart
lib/app/updates/updates_page.dart

(note: the padding fix visible in this screensht is in the other PR)
(another note: the search needs to be done in a different PR and is currently not working on this page)
Fixes #858

Updates: move the tabs to the header as on the other pages for consistency

---

lib/services/packagekit/package_service.dart
test/services/package_service_test.dart

Fetch package groups in single transaction

---

lib/app/common/app_icon.dart

wrap AppIcon in RepaintBoundary

---

lib/app/common/snap/snap_controls.dart

Wrong translation procuces overflow on `AppPage`

---

lib/app/app_model.dart

Launcher entry: update counter and progress bar simultaneously

---

lib/app/common/snap/snap_controls.dart
lib/services/snap_service.dart
lib/snapd_change_x.dart

Adds a progress indicator for snap operations
[Screencast from 2023-01-31 13:13:51.webm](https://user-images.githubusercontent.com/113362648/215757099-02af8531-1d8f-457e-afbc-ffa15ba882fd.webm)
I'll add something similar for packagekit in a separate PR.
Ref #906

Snap progress indicator

---

lib/app/explore/explore_page.dart
lib/app/explore/start_page.dart

Detach `ExploreModel` from `StartPage` and just pass a list of snaps and the `SnapSection` to the constructor

---

lib/app/explore/explore_header.dart
lib/app/explore/explore_model.dart
lib/app/explore/explore_page.dart
lib/app/explore/search_page.dart
lib/app/installed/installed_header.dart
lib/app/installed/installed_model.dart
lib/app/installed/installed_page.dart

detach the `ExploreHeader` and `InstalledHeader` from any models

---

lib/app/app.dart
lib/app/common/app_rating.dart
lib/app/common/rating_model.dart
lib/main.dart
lib/services/odrs_service.dart
pubspec.yaml

NOTE: Only _ratings_ - not reviews. :)
| Explore | Snap | Deb |
|---|---|---|
| ![Screenshot from 2023-01-31 21-38-54](https://user-images.githubusercontent.com/140617/215878270-d3a82a10-6513-41b7-b8f2-f7e142a59b2a.png) | ![Screenshot from 2023-01-31 21-39-14](https://user-images.githubusercontent.com/140617/215878285-b6afb9ba-18a4-4be1-90cf-27e6ddd7919e.png) | ![Screenshot from 2023-01-31 21-39-19](https://user-images.githubusercontent.com/140617/215878303-f0cd3cb2-cf43-4173-8381-51b2a4b54174.png) |
Ref: #872

ODRS ratings

---

lib/app/explore/explore_model.dart
lib/app/explore/explore_page.dart
lib/app/explore/search_page.dart

ExplorePage: get rid of FutureBuilder

---

lib/app/common/app_data.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/review_model.dart
lib/app/common/snap/snap_page.dart
lib/services/odrs_service.dart

This PR implements the _fetching_ of reviews from ODRS. (Up/down-voting, reporting, and submitting reviews are not included in this.)
Ref: #872

ODRS reviews

---

lib/app/common/app_page/app_reviews.dart

|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/15329494/216001359-7897bbdf-6143-4673-859b-63d73712ef9d.png)|![image](https://user-images.githubusercontent.com/15329494/216001583-2f6a5892-ae92-4fad-971f-b3fddd3de5ba.png)|

AppReviewsDialog: improve padding

---

lib/app/app.dart
lib/app/app_model.dart

Ref #609 
Still works as expected (badges ans spinner)

AppModel: use context select

---

lib/app/installed/installed_header.dart

Installed page - update icon/button styling

---

lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/l10n/app_en.arb
lib/services/packagekit/package_service.dart

Show deb dependency sizes

---

lib/app/common/packagekit/package_model.dart
lib/app/updates/update_dialog.dart

[Screencast from 2023-02-03 13:04:40.webm](https://user-images.githubusercontent.com/113362648/216599409-49301ed6-6f49-4005-8a8a-315c3e4eacc8.webm)
Fix #951

PackageModel: make checkDependencies optional in init

---

lib/app/common/packagekit/package_page.dart

Before:
[Screencast from 2023-02-03 17:31:09.webm](https://user-images.githubusercontent.com/113362648/216656739-4a442bf9-3ebc-47b8-b902-6ac8863f111d.webm)
After:
[Screencast from 2023-02-03 17:32:00.webm](https://user-images.githubusercontent.com/113362648/216656750-f009a368-c971-48fa-9a31-82d34f8f16a8.webm)

fix scroll behavior in dependency dialog

---

lib/app/settings/settings_page.dart

> ...What about an icon for the within configure button?...
https://github.com/ubuntu-flutter-community/software/issues/904#issuecomment-1408685907

Add gear icon ⚙️ 

---

lib/app/settings/settings_page.dart
lib/l10n/app_en.arb

SettingsPage: add license button and route, improve layout

---

lib/app/updates/package_updates_page.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/966

Added text color to albino log

---

lib/app/settings/settings_model.dart
lib/app/settings/settings_page.dart

- make properties nullable
- make const private to not show up in code completion elsewhere

SettingsModel: clean up

---

lib/app/common/app_page/app_page.dart

https://user-images.githubusercontent.com/15329494/216814665-92f3c848-2d9c-4d23-9820-2167609323f0.mp4
Bonus: use YaruDialogTitlebar
Fixes #971

AppPage Gallery dialog should resize on window size change

---

lib/app/common/app_page/app_page.dart

Sorry, forgotten to change the title :)

AppPage Gallery Dialog: use appData.name as title

---

lib/app/updates/snap_updates_model.dart

https://user-images.githubusercontent.com/15329494/216808762-4eec5bf0-2107-4d85-aeec-61021ded83e4.mp4
Fixes #969

SnapUpdates: refresh all should not ask for password before every update

---

lib/app/collection/collection_model.dart
lib/app/collection/collection_page.dart

- bring back snap sort popup
- always show updates at top (if any are there)
Ref #954

Collection: sort snaps by update and SnapSort

---

lib/services/packagekit/package_service.dart
test/services/package_service_test.dart

Update list of installed packages upon installation/removal

---

lib/app/collection/collection_page.dart

fix tile shape and divider based on list length and index

Collection: fix tile shape and divider

---

lib/app/collection/simple_snap_controls.dart

From @anasereijo's comment here https://github.com/ubuntu-flutter-community/software/discussions/357#discussioncomment-4895891
Before:
After:

Hide disabled Open button for snaps

---

lib/services/packagekit/package_service.dart

PackageService: fix isInstalled

---

lib/app/collection/collection_page.dart
lib/app/common/packagekit/package_controls.dart
lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/l10n/app_en.arb
lib/services/packagekit/package_service.dart
lib/services/packagekit/package_state.dart
pubspec.yaml
test/services/package_model_test.dart
test/services/package_service_test.dart

PackageKit equivalent of #916.
Depends on https://github.com/canonical/packagekit.dart/pull/26.
[Screencast from 2023-02-02 15:56:06.webm](https://user-images.githubusercontent.com/113362648/216359188-9f6adcd7-b5b1-401e-8625-df6fddc11037.webm)
Ref #906

Packagekit progress indicator

---

lib/app/collection/collection_model.dart
lib/app/collection/collection_page.dart

CollectionModel: make _installedSnaps null at start

---

lib/app/app.dart
lib/app/common/snap/snap_section.dart
lib/app/explore/explore_page.dart

@local-optimum I think you mentioned the importance of "iot" and "server and cloud" somwhere (was it in the meeting?)
This PR adds two more shortcuts to the sidebar
- iot
- server and cloud
We can add more in the future if you like

App: add more shortcut pageItems

---

lib/app/explore/explore_model.dart
lib/app/explore/explore_page.dart
lib/app/explore/section_grid.dart
lib/app/explore/start_page.dart
lib/services/snap_service.dart
test/widget_test.dart

[Screencast from 2023-02-09 16:06:59.webm](https://user-images.githubusercontent.com/113362648/217855766-30062088-2cea-44f7-a42e-f2bb1f872c80.webm)

`StartPage`: show appstream data as soon as possible

---

lib/app/collection/collection_model.dart
lib/app/collection/collection_page.dart
lib/app/collection/package_updates_page.dart
lib/app/collection/simple_snap_controls.dart
lib/app/common/snap/snap_section.dart
pubspec.yaml

- fix wrong padding for expand icon in the deb updates/collection page
- new app grid icon as discussed
- new all snap category icon as discussed
- fixes to when show which button/spinner in the header
Closes #1008 
Ref #1005

CollectionPage: improve icon and design and fix bugs

---

lib/app/explore/offline_page.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/1012

Changed Offline text color to grey

---

lib/app/common/app_page/app_reviews.dart

Fixes overflow in the review/rating page and the popup dialogue.
I also grouped together all of the icon buttons, making it all a little more balanced. wdyt?
We should probably also increase the minimum size of the window.
Before:
https://user-images.githubusercontent.com/73116038/217972759-a2d20785-f976-4bbe-b45b-8e1112ea55ef.mp4
After:
https://user-images.githubusercontent.com/73116038/217972778-5841626b-ad91-4d24-ade3-33ecc90ce5bc.mp4
Fixes #898

Fix overflow error in review/ratings

---

lib/app/common/app_page/app_reviews.dart

[Reviews/Rating] expand inkwell to include blank space

---

lib/app/common/app_page/app_reviews.dart

remove extra bottom padding in review dialog

---

lib/app/common/app_page/app_reviews.dart

remove awkward review carousel cutoff

---

lib/app/collection/collection_page.dart
lib/app/common/app_format_popup.dart

- Display an indicator stacked on the package format selector if updates are available in another format ;
- Display a badge against each package format, indicating how much updates are available.
[Capture vidéo du 2023-02-10 12-22-53.webm](https://user-images.githubusercontent.com/36476595/218081846-da90e793-c4ac-4e1a-a3f6-96c95c489401.webm)
Fixes #1026

Collection page: show badge on app format selector

---

pubspec.yaml

Pubspec: Upgrade handy_window

---

integration_test/software_test.dart
lib/app/collection/collection_page.dart
lib/app/collection/collection_tile.dart
lib/app/collection/package_collection.dart
lib/app/collection/snap_collection.dart

No visual changes, except that the FAB now also shows up for the snap collection if scrolled down
Fixes #1025

CollectionPage: organize

---

lib/app/collection/package_updates_page.dart

Package updating page: add padding

---

lib/app/common/packagekit/package_model.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/1043

Only show date in ReleasedAt

---

lib/app/explore/section_banner.dart

- smaller icons
- better alignment
- slogan + title ( we need better text here... )
ref: ![](https://user-images.githubusercontent.com/36884067/218127897-45afd0de-dda9-488c-8204-8e4de705a123.png)

Bring section banner closer to design

---

lib/app/common/packagekit/package_page.dart

PackagePage: set appIsInstalled in AppPage

---

lib/app/explore/explore_model.dart

ExploreModel: enable packageKit before loading StartPage components

---

lib/app/collection/package_updates_page.dart
pubspec.yaml

Remove the package updating details

---

lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_page.dart
lib/l10n/app_en.arb

SnapPage: add a share button

---

lib/app/common/app_page/publisher_name.dart
lib/l10n/app_en.arb

Fixes https://github.com/ubuntu-flutter-community/software/issues/1058

Snap account icons

---

lib/app/common/app_page/app_header.dart
lib/l10n/app_en.arb

Releated to https://github.com/ubuntu-flutter-community/software/pull/1056#pullrequestreview-1298519888

Add tooltip for share icon

---

lib/app/app.dart
lib/app/app_model.dart
lib/app/common/close_confirmation_dialog.dart
lib/main.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.yaml

This is a pre-requisite for
- #978

Switch to yaru_window

---

lib/app/common/app_banner.dart

AppBanner: better publishername guessing

---

lib/app/collection/collection_page.dart
lib/app/common/app_page/app_page.dart
lib/app/common/constants.dart
lib/app/explore/explore_page.dart

Fix Title alignment

---

lib/app/common/snap/snap_controls.dart

https://user-images.githubusercontent.com/15329494/219354485-be88a826-3b71-46b3-a7cd-15f8855d1ef8.mp4
Fixes #1069

Fix: Can't switch snap tracking channel without reinstalling

---

lib/app/collection/collection_model.dart

CollectionPage: fix NPE with early search

---

lib/app/collection/package_collection.dart
lib/app/collection/snap_collection.dart
lib/app/common/app_banner.dart
lib/app/common/app_data.dart
lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_page.dart
lib/app/common/app_page/publisher_name.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart
lib/app/explore/explore_model.dart
lib/app/explore/explore_page.dart
lib/app/package_installer/package_installer_page.dart

https://user-images.githubusercontent.com/15329494/219559999-d48fc32a-0e03-4282-a5bb-300ad1bd0008.mp4
@d-loose aaaaaalmost :) 
1) make click on publisher search with the publisher username as query
2) don't do this when on the collectionpage
TODO:
Fixes #1016

Make publisher name click search for publisher

---

lib/app/common/app_page/app_header.dart

Issue1061 apppage title overflow

---

pubspec.yaml

There're some mild changes in the PR branch - should have set the reference to a fixed commit before, sorry!

fix snapd.dart git ref until PR is merged

---

lib/app/app_model.dart
test/widget_test.dart

AppModel: return sum of snap and deb updates

---

lib/app/explore/explore_page.dart

ExplorePage: reset searchQuery in initState

---

lib/app/collection/simple_snap_controls.dart
lib/app/common/app_page/app_header.dart

I initially wanted to use fontsize 24 for the title, but didn't want to change the sizebox height. Now it looks like we have to do that anyway to prevent overflow with special characters.
WDYT @Feichtmeier ?
Fixes #1099

Changed sizebox height

---

lib/app/collection/simple_snap_controls.dart
lib/l10n/app_en.arb

Things got really messy over in https://github.com/ubuntu-flutter-community/software/pull/1098, so here's a second attempt at (hopefully) fixing #988 😸

Alert dialog for removing snap

---

lib/app/collection/package_update_dialog.dart

Added width to container. Fixes expand sections to full width #1114

Issue #1114

---

lib/app/explore/section_banner.dart

Removed transparency and added bold font.
@anasereijo 
Before / After:

Font tweaks for section banners

---

lib/app/common/snap/snap_section.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/1011
Discussed here: https://github.com/ubuntu-flutter-community/software/discussions/1014#discussioncomment-5077295
This was harder than it looks! What we had was already pretty good for some categories. I felt a bit constraint by the limited selection, but tried my best to match the colors to a category. WDYT? @Zoospora @Feichtmeier @Jupi007

New banner gradients

---

lib/app/common/snap/snap_page.dart

SnapPage: use outline for snapchannel button

---

lib/app/common/app_data.dart
lib/app/common/app_page/app_infos/app_infos.dart
lib/app/common/app_page/app_page.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/app_rating.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/rating_chart.dart
lib/app/common/rating_model.dart
lib/app/common/snap/snap_page.dart
lib/l10n/app_en.arb

Implement Ratings and Reviews redesign 

---

lib/app/common/app_page/app_reviews.dart

ReviewRatingBar: simplify alignment and detachment

---

lib/app/collection/collection_page.dart
lib/l10n/app_en.arb

Testing! https://github.com/ubuntu-flutter-community/software/discussions/977

Replace Collection with Manage

---

lib/app/common/app_page/app_description.dart

AppPage description text aligned left

---

lib/app/common/packagekit/packagekit_filter_button.dart
lib/l10n/app_en.arb

The string **The type of package** is very long and should be shorter. I suggest **Package type** or if that doesn't stick **Type of package**.
Screenshot for your pleasure 😎

Shorter translation for Package type

---

lib/app/common/app_page/app_format_toggle_buttons.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart

Fixes https://github.com/ubuntu-flutter-community/software/issues/1120

appformat toggle button fontweight

---

.github/workflows/cla-check.yaml

I've noticed this difference to the other files. Maybe it makes a difference 🤷 
Ref #1054

Attempt to fix CLA

---

lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/app/explore/explore_model.dart
lib/services/packagekit/package_service.dart

| - | - |
| ![image](https://user-images.githubusercontent.com/113362648/221901504-234bbac1-fd91-49c1-ae81-a19722cb924b.png) | ![image](https://user-images.githubusercontent.com/113362648/221901341-5b09fce7-f4d3-48bc-8a22-10c7ba67beb9.png) |

PackagePage: show dependency sizes

---

lib/app/explore/section_banner.dart
lib/app/explore/start_page.dart

SectionBanner: fill with appfindings rather than snaps

---

lib/app/common/packagekit/dependency_dialogs.dart
lib/app/common/packagekit/package_controls.dart
lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/l10n/app_en.arb
lib/services/packagekit/package_service.dart
pubspec.yaml
test/services/package_model_test.dart

Lists dependencies of installed packages on the app page and shows a dialog that provides the user with the option to remove unneeded dependencies, when removing a package.
[Screencast from 2023-03-01 13-45-29.webm](https://user-images.githubusercontent.com/113362648/222143285-316dc134-384a-42f0-b610-6dfd6a6aa372.webm)
Fix #980

Dependency removal

---

lib/app/explore/section_grid.dart

fix(UI): explore page snaps have lower case letters

---

lib/app/common/app_page/app_infos/additional_information.dart
lib/app/common/app_page/app_infos/publisher_info_fragment.dart

- use horizontal 20 pixel spacing
- move the icon to the start
- publisherName.replaceAll(' ', '\u00A0')
[Bildschirmaufzeichnung vom 14.03.2023, 11:23:30.webm](https://user-images.githubusercontent.com/15329494/224971306-5b91aa1c-d30e-452e-9b8f-c2cbd63e27db.webm)
CC @anasereijo

Additional Information fixes

---

lib/app/common/app_page/app_reviews.dart

I couldn't make it work like you mentioned in #1173 @Feichtmeier but here's a solution. Looks better in the app than this screenshot.

Issue1173 - review divider

---

lib/app/common/search_field.dart

Okay, please check this code - It took me all day and I must have visited every site on Google looking for a way to fix this 😅
I also made the clear icon a bit stronger. WDYT?

Changes searchfield font size

---

lib/app/collection/collection_model.dart

This PR shows the list of installed apps whilst a snap is in the process of being installed.
https://user-images.githubusercontent.com/73116038/225945155-5af8a9d2-e540-48eb-9746-29d448924190.mp4
Ref #1165 
Fixes #1142

show installed apps when installing snap

---

lib/app/common/app_page/app_infos/app_infos.dart
lib/app/explore/section_grid.dart

Closes #1185 
|   | 
|---|
| ![Screenshot from 2023-03-24 02-47-36](https://user-images.githubusercontent.com/42430941/227365001-4456f4f4-f6bd-4ab5-8db0-7dff978fb671.png)  |

feat(UI): add total ratings along with reviews

---

lib/app/collection/collection_page.dart
lib/app/collection/package_collection.dart

[Bildschirmaufzeichnung vom 24.03.2023, 09:07:30.webm](https://user-images.githubusercontent.com/15329494/227461517-47197f11-18da-4c62-8f30-a45f94141c68.webm)
Fixes #1009

Make collection page 📄 lazy 🦥 load its packages

---

.github/workflows/analyze.yml
.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/test.yml

Until the project and its dependencies have been migrated to Flutter 3.10 and Dart 3.0.

ci: pin flutter version to 3.7

---

.github/workflows/analyze.yml
.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/test.yml
lib/app/common/app_banner.dart
lib/app/common/loading_banner_grid.dart
lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/app/explore/search_page.dart
lib/app/settings/settings_page.dart
pubspec.yaml
snap/snapcraft.yaml

Needed to fork and fix the liquid progress indicator (I will try to reach the maintainer for a PR merge)
But it works now and the integration test is also fixed (flutter version...)

Upgrade to dart 3 and flutter 3.10

---

lib/app/settings/settings_page.dart

as suggested in https://github.com/ubuntu-flutter-community/software/pull/1234#discussion_r1197691654 by @jpnurmi

SettingsPage: simplify theme switch logic

---

lib/services/packagekit/package_service.dart
test/services/package_service_test.dart

Temporary workaround for PackageKit-related AppArmor denials.
Fix #1215

fix(packagekit): ensure packagekit daemon is active

---

pubspec.yaml

See https://github.com/ubuntu-flutter-community/software/issues/941#issuecomment-1568101689

chore: pin snapd.dart 0.4.8

---

lib/app/app.dart
lib/app/app_model.dart
lib/app/common/app_banner.dart
lib/app/explore/explore_page.dart
lib/app/explore/section_grid.dart
lib/app/explore/start_page.dart

[Bildschirmaufzeichnung vom 2023-06-04, 12-24-43.webm](https://github.com/ubuntu-flutter-community/software/assets/15329494/3b63a7a6-b21f-40bf-8886-74c2029dee4e)
Fixes #1254

 let the deb icons fade in/out to indicate that the mapping is loading

---

lib/l10n/app_en.arb

Fix indentation and remove extra whitespace to avoid unrelated changes with auto-formatting enabled.

chore: fix app_en.arb formatting

---

lib/app/common/app_page/app_reviews.dart

| - | - |
|![grafik](https://github.com/ubuntu-flutter-community/software/assets/15329494/063f317f-f3b0-4415-8d6b-7c8d03470116) | ![grafik](https://github.com/ubuntu-flutter-community/software/assets/15329494/1f30ecf9-8a82-413f-b5e3-e01126e38377)|
Fixes #1231

Your review dialog overflow

---

lib/app/collection/collection_page.dart

CollectionPage: move spinner to button

---

lib/src/detail/detail_page.dart
lib/src/snapd/snap_provider.dart
test/detail_page_test.dart
test/test_utils.mocks.dart

UDENG-791
[Screencast from 2023-07-20 11-24-35.webm](https://github.com/ubuntu/app-store/assets/113362648/eb94a2e1-810b-4d4a-ae70-68d81bbc1454)

feat: snap channels (install/refresh)

---

lib/src/store/store_app.dart
lib/src/store/store_pages.dart

|---|---|
| ![image](https://github.com/ubuntu/app-store/assets/140617/8fa46ab6-88d9-41ac-a0ff-eafa94b72f8b) | ![image](https://github.com/ubuntu/app-store/assets/140617/7cc2ea16-6e19-471f-abda-5942efeda75c) |

feat(navi-rail): push manage & about to the bottom

---

lib/src/search/search_field.dart

|---|---|
| ![image](https://github.com/ubuntu/app-store/assets/140617/4efe9088-a8cc-42d5-b3c4-c4b08706e7ec) | ![Screenshot from 2023-07-20 14-17-19](https://github.com/ubuntu/app-store/assets/140617/0127d9af-06b3-4312-a34c-86637d5bf1f0) |
| ![image](https://github.com/ubuntu/app-store/assets/140617/62b3acac-7cd5-42f3-8aab-1bc974fef310) | ![Screenshot from 2023-07-20 14-17-59](https://github.com/ubuntu/app-store/assets/140617/3c54c433-5a51-49bb-acca-5f92e8ea67bd) |
| ![image](https://github.com/ubuntu/app-store/assets/140617/5b0687eb-679a-4851-b8ab-f93c1bcfa166) | ![Screenshot from 2023-07-20 14-17-31](https://github.com/ubuntu/app-store/assets/140617/ab64e423-25fd-4983-b31f-de0138a92644) |
| ![image](https://github.com/ubuntu/app-store/assets/140617/4447c1b9-3ec6-46b3-9 …

feat(search): remove unfocused border & reduce height

---

lib/src/detail/detail_page.dart
lib/src/snapd/snap_model.dart
test/test_utils.dart

feat(detail): add version to channel dropdown

---

lib/constants.dart
lib/src/store/store_app.dart
lib/src/store/store_pages.dart
lib/src/widgets/snap_grid.dart
pubspec.yaml

feat(store): switch to master-detail

---

lib/main.dart
lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
pubspec.yaml
test/detail_page_test.dart

UDENG-1048
Logic to be refined later together with the rest of the snap metadata.

feat(detail): add localized 'last updated' date

---

pubspec.yaml

- https://github.com/ubuntu/yaru_widgets.dart/pull/725

chore(deps): update yaru_widgets to ^2.6.0

---

pubspec.yaml

- https://github.com/canonical/snapd.dart/pull/97

chore(deps): update snapd to ^0.4.11

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
lib/src/snapd/snap_model.dart
pubspec.yaml
test/detail_page_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

feat(detail): implement newest snap metadata UI

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb

UDENG-1048
[Screencast from 2023-08-01 16-29-51.webm](https://github.com/ubuntu/app-store/assets/113362648/2d8a1df3-57cd-4185-abba-adb996e33c14)

feat(detail): implement channel dropdown UI

---

lib/src/detail/detail_page.dart
lib/src/snapd/snap_model.dart
test/detail_page_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

feat: hide screenshot gallery if no screenshots are available

---

lib/src/explore/explore_page.dart
lib/src/l10n/app_en.arb
lib/src/snapd/snap_category_enum.dart
lib/src/widgets/snap_grid.dart

UDENG-1048
[Screencast from 2023-08-04 17-41-02.webm](https://github.com/ubuntu/app-store/assets/113362648/4d647ea4-7541-41d5-8a2d-de8453d2a369)
Will import the rest of @Zoospora's gradient colors later.

feat: add explore page banner

---

lib/layout.dart
lib/src/category/category_page.dart
lib/src/detail/detail_page.dart
lib/src/explore/explore_page.dart
lib/src/search/search_page.dart
lib/src/widgets/snap_card.dart
lib/src/widgets/snap_grid.dart

* Make `SnapGrid` a `Sliver`
* Make `ResponsiveLayout` extend `InheritedWidget`
* Add `ResponsiveLayoutScrollView` - a `CustomScrollView` that wraps its children in `SliverPadding`s with padding set by the `ResponsiveLayout`

refactor: ResponsiveLayoutBuilder + Slivers

---

lib/src/explore/explore_page.dart
lib/src/snapd/snap_category_enum.dart

UDENG-1048
* Add category icons
* Show categories on explore page

feat: category list

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
test/detail_page_test.dart

feat: localize snap confinement and add shield icon

---

lib/src/l10n/app_en.arb
lib/src/manage/manage_model.dart
lib/src/manage/manage_page.dart
lib/src/snapd/updates_model.dart
lib/src/widgets/clickable.dart
lib/widgets.dart
test/manage_page_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

UDENG-1048
First iteration of the manage page design implementation.
[Screencast from 2023-08-09 15-31-38.webm](https://github.com/ubuntu/app-store/assets/113362648/96f94082-bf6e-4e08-9940-4b8c404051bc)
Narrow layout still needs some work:

feat: implement basic manage page UI

---

lib/layout.dart
lib/src/manage/manage_page.dart

UDENG-1048
[Screencast from 2023-08-09 17-57-26.webm](https://github.com/ubuntu/app-store/assets/113362648/6de07050-1647-4666-8a36-cdf29368fc82)

feat: implement small-screen layout for manage page

---

lib/src/category/category_page.dart
lib/src/explore/explore_page.dart
lib/src/manage/manage_page.dart
lib/src/search/search_field.dart
lib/src/search/search_page.dart
lib/src/search/search_provider.dart
lib/src/snapd/snap_category_enum.dart
lib/src/store/store_app.dart
lib/src/store/store_navigator.dart
lib/src/store/store_providers.dart
lib/src/store/store_routes.dart
lib/src/widgets/snap_title.dart
test/store_navigator_test.dart
test/store_routes_test.dart

Makes 'query' optional and adds a 'category' search parameter. This makes it possible to perform a search with a pre-selected category filter.
[Screencast from 2023-08-10 15-16-20.webm](https://github.com/ubuntu/app-store/assets/113362648/e388302f-1260-4cca-9f67-6182005f9a75)

feat: generalize search page

---

lib/src/store/store_providers.dart
test/initial_route_test.dart

Handles 'snap://foo' as an optional positional cli argument

feat: add 'snap://' argument handler

---

snap/snapcraft.yaml

Workaround pub get stack overflow

Fix launchpad builds

---

lib/src/about/about_page.dart

|Before|After|
|-|-|
|![Screenshot from 2023-08-17 14-57-56](https://github.com/ubuntu/app-store/assets/113362648/03e34daf-a27a-4f82-9fa3-805a1af863c1)|![Screenshot from 2023-08-17 14-56-02](https://github.com/ubuntu/app-store/assets/113362648/c51c6fbc-83e5-4c7d-9e64-169db2a2fec0)|

feat: remove placeholders from about page

---

lib/src/l10n/app_en.arb
lib/src/search/search_page.dart
test/search_page_test.dart

[Screencast from 2023-08-16 16-19-08.webm](https://github.com/ubuntu/app-store/assets/113362648/7241ab22-5a4c-4d86-a1ba-f2a517f4d90f)

feat: show message if search results are empty

---

lib/snapd.dart
lib/src/l10n/app_en.arb
lib/src/manage/local_snap_providers.dart
lib/src/manage/manage_page.dart
lib/src/search/search_page.dart
lib/src/search/search_provider.dart
lib/src/snapd/snap_l10n.dart
lib/src/snapd/snap_sort.dart
test/manage_page_test.dart
test/search_page_test.dart

UDENG-797
* Generalizes the sorting functionality from the search page so that it can be reused elsewhere
* Adds sorting and filtering to the manage page
[Screencast from 2023-08-18 17-29-35.webm](https://github.com/ubuntu/app-store/assets/113362648/9d30c8eb-65ab-4b14-b70c-ef9e89984a21)

feat: improve sorting and filtering

---

lib/src/search/search_page.dart
lib/src/search/search_provider.dart

fix(search): default to snaps when initial category is given

---

lib/config.dart
lib/main.dart
snap/snapcraft.yaml
test/config_service_test.dart

feat: ratings env vars

---

snap/snapcraft.yaml

work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253

fix(snap): work around dart pub get crash

---

lib/src/search/search_field.dart

UDENG-1481
Fix #1400
Refactors the search autocompletion: 
* Removes 'fake' `AutoCompleteOption`s that were previously used to build the dividers and 'Snap/Debian packages' titles. This ensures they can't be accidentally selected via the arrow keys.
* Builds dividers and titles in the `optionsViewBuilder` instead
* Makes "See all results for {query}" the default option (as requested by @anasereijo)

fix(search): autocomplete behavior

---

lib/src/snapd/snap_search.dart
test/snap_search_test.dart

feat: filter snap search query

---

lib/src/manage/manage_page.dart
lib/src/snapd/snap_model.dart
pubspec.yaml
test/manage_page_test.dart
test/snap_model_test.dart
test/test_utils.dart

UDENG-1487
Fixes #1406, #1414
Also prevents division by zero in the progress calculation

fix(manage): update all button

---

lib/src/explore/explore_page.dart
lib/src/l10n/app_en.arb
lib/src/snapd/snap_category_enum.dart
lib/src/snapd/snap_page.dart
lib/src/store/store_pages.dart
lib/src/widgets/app_info_bar.dart

@anasereijo, as discussed:
* Adjusted margins/paddings on the snap page
* Removed bottom margins
* Added the summary to the description section
* Changed labels to sentence case
We'll need to come back to color and text theme tweaks later on - sorry!

feat: UI tweaks

---

lib/src/snapd/snap_model.dart
test/snap_model_test.dart
test/test_utils.dart

UDENG-1486
Fix #1405
[Screencast from 2023-09-29 17-41-29.webm](https://github.com/ubuntu/app-center/assets/113362648/adc0a674-9964-4dfe-9a25-f349fc070683)

feat(snap): fetch active change

---

lib/src/store/store_routes.dart
test/store_navigator_test.dart
test/store_routes_test.dart

Adds unit tests for deb routes

test: deb routes

---

lib/src/snapd/snap_page.dart

fix(snap-page): fix channel dropdown item height

---

pubspec.yaml

chore: bump ubuntu_widgets

---

CONTRIBUTING.md

In this PR:
- Adding a requirement entry to CONTRIBUTING.md.
fix #1460

docs: Adding the Flutter Linux prerequisites to CONTRIBUTING.md

---

packages/app_center/lib/src/snapd/snap_category_enum.dart
packages/app_center/lib/src/store/store_pages.dart
packages/app_center/pubspec.yaml

[Screencast from 2023-12-18 20-39-29.webm](https://github.com/ubuntu/app-center/assets/72045785/df49e95f-8911-40ad-b209-f54efaa876e3)

[store_page]: change the button icons based on `selected`

---

packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/lib/src/widgets/app_info_bar.dart

1. Show the mouse hand cursor on the uninstall button
2. Added the version in the snap info bar and made them selectable
3. Made the description selectable

snap_page: Enhancement in the view

---

packages/app_center/lib/src/manage/manage_page.dart

before:
after:
@anasereijo @BLKKKBVSIK

manage_page: fix the update button oversizing

---

melos.yaml
packages/app_center/test/snapd_cache_test.mocks.dart
packages/app_center/test/snapd_watcher_test.mocks.dart
packages/app_center/test/test_utils.mocks.dart
packages/app_center_ratings_client/lib/src/chart.freezed.dart
packages/app_center_ratings_client/lib/src/user.freezed.dart
snap/snapcraft.yaml

Attempt to fix launchpad build failures previously fixed [here](https://github.com/ubuntu/app-center/pull/1389).

fix(snap): don't run pub get in parallel

---

snap/snapcraft.yaml

Might help to apply the correct setting *before* running melos .. :facepalm:

fix(snap): apply melos setting before running melos

---

packages/app_center/lib/src/store/store_app.dart

fix: add missing high contrast themes

---

packages/app_center/lib/src/manage/manage_page.dart

[manage_page]: fix the buttons alignment

---

.github/workflows/ci.yaml
.github/workflows/integration-test.yaml

This reverts commit 228287aa8ec6087208bee51c167f7ad71aa11224.

fix: Revert "fix(ci): temporarily skip apt update if it fails"

---

packages/app_center/lib/src/packagekit/packagekit_service.dart
packages/app_center/test/packagekit_service_test.dart
packages/app_center/test/test_utils.dart
packages/app_center/test/test_utils.mocks.dart

Adds packagekit methods to retrieve local package information and install a local package.
Ref #1407
UDENG-1490

feat(packagekit): add local deb methods

---

packages/app_center/lib/src/snapd/snap_page.dart

fix(snap_page): hide empty links

---

packages/app_center/lib/deb/local_deb_page.dart
packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/test/local_deb_page_test.dart

fix(local_deb_page): install->installed after finishing

---

packages/app_center/lib/store/store_app.dart

before
https://github.com/ubuntu/app-center/assets/15329494/225b19e7-d8ba-4246-966b-0b7f5d79773e
after
https://github.com/ubuntu/app-center/assets/15329494/53c13ebf-aef4-407c-924e-45a87d2322c0

fix(StoreApp): don't let the searchbar overflow

---

packages/app_center/lib/manage/local_snap_providers.dart
packages/app_center/lib/manage/local_snap_providers.g.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/manage/updates_model.dart
packages/app_center/lib/manage/updates_model.g.dart
packages/app_center/lib/snapd/snap_model.dart
packages/app_center/lib/snapd/snap_model.g.dart
packages/app_center/lib/snapd/snap_page.dart

[Screencast from 2024-07-17 21-45-32.webm](https://github.com/user-attachments/assets/85ab5ee3-f764-4474-b27e-63fbb1259356)
Closes #1745

feat: Uninstall snaps from the manage page

---

packages/app_center/lib/store/store_app.dart
packages/app_center/test/manage_page_test.dart
packages/app_center/test/store_app_test.dart

feat: don't show error when cancelling auth

---

packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/xdg_cache_manager.dart
packages/app_center/test/manage_page_test.dart

~Will add a test before merging~

feat: Show quit to update on open snaps

---

packages/app_center/lib/ratings/ratings_l10n.dart

This PR fixes the low contrast of rating labels #1746

fix: Rating labels low contrast

---

packages/app_center/lib/src/l10n/app_en.arb

fix: Update manage page label

---

packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/src/l10n/app_en.arb

See https://github.com/ubuntu/app-center/pull/1787#discussion_r1725242693

fix: restore manage page title

---

packages/app_center/lib/store/store_app.dart

I have no way to verify that this works, it simply uses the code suggested in #1732, so let's keep the issue open until someone with a touch screen can verify.

fix: Support scrolling on touchscreens

---

packages/app_center/lib/explore/explore_page.dart

fix: Move featured section to top of explore page

---

packages/app_center/lib/snapd/snap_category_enum.dart
packages/app_center/lib/widgets/banner.dart

fix: Correct gradient for featured banner

---

packages/app_center/lib/constants.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/search/search_field.dart

[Screencast from 2024-10-04 16-31-39.webm](https://github.com/user-attachments/assets/85998e6a-e416-46af-a10a-7d745a5e9f0d)
Fixes: #1832

fix: Height of search fields should be static

---

packages/app_center/lib/manage/manage_page.dart

fix: Move up and make search and sort row smaller

---

packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/manage/snap_actions_button.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/pubspec.yaml

Accidentally merged the other PR with the dependency override (and a missed name change).

chore: Bump yaru to 5.3.1

---

packages/app_center/lib/widgets/category_snap_list.dart

feat: show 12 snaps in charts for better column alignment

---

packages/app_center/lib/store/store_app.dart

This PR should encompass most of the theme-only fixes for contrast issues. This does not include fixes that are required at a widget level.
Relevant accessibility issues:
- 1861761 (search contrast)
- 1860625 (version info)
- 1860587 (version info)
---
UDENG-6005

fix: Contrast theme issues

---

packages/app_center/lib/about/about_page.dart
packages/app_center/lib/snapd/snap_report.dart

This makes all links underlined, and removes the background color to text inputs.
---
UDENG-6005

fix: More contrast adjustments
