lib/store_app/updates/updates_page.dart

Packagekitprogress is weird and seems inaccurate. Fake the 5-10 seconds with a smooth animation

UpdatesSplashScreen: replace weird progress with fake

---

lib/store_app/common/snap_content.dart

The hover should only be displayed by the mousecursor as with the buttons on the left and right, thus removing the hover color fixes the issue
Fixes #121

Clip SnapDialog Carousel mouse over correctly when scrolled off screen

---

lib/store_app/common/snap_dialog.dart
lib/store_app/common/snap_model.dart
lib/store_app/common/snap_page_header.dart

@oSoMoN @Jupi007 I didn't find how to get a iso norm but localized so I switched back to your iso norm preference, however, this time without making the view any more "intelligent". I would really like to keep the view as stupid as possible (like in the rest of the views).
Fixes #129

SnapModel: localize install date tooltip

---

lib/store_app/updates/updates_page.dart

UpdatesPage: do not show updating status in the view, this has not any benefit for the user.
| - | - |
| ![grafik](https://user-images.githubusercontent.com/15329494/187684394-291ca283-9ffd-4f1a-abeb-6dca4b68b6aa.png) | ![grafik](https://user-images.githubusercontent.com/15329494/187684528-00aa6799-6229-485b-a960-9eb9513426e7.png) |
Fixes #137

UpdatesPage: do not show updating status in the view

---

snap/snapcraft.yaml

See https://github.com/jpnurmi/flutter_raster_cache_bug for details.
Fixes #189.

Pin flutter at 3.0.5 to workaround rendering issues with 3.3.

---

snap/snapcraft.yaml

Don't run flutter upgrade when source-tag is set, it fails with no channel set error

Don't run flutter upgrade when source-tag is set

---

lib/store_app/updates/updates_page.dart

[Bildschirmaufzeichnung vom 21.09.2022, 14:39:36.webm](https://user-images.githubusercontent.com/15329494/191505988-ec6b67d0-ab17-454d-af1c-28a0543c4b68.webm)
(0,00013 ∙ x^2) − 20 is a great function for hPadding so we do not see visual jumps like before

UpdatesPage: smooth out padding

---

lib/store_app/common/media_tile.dart

[Capture vidéo du 21-09-2022 22:43:30.webm](https://user-images.githubusercontent.com/36476595/191606974-eecd7f07-7187-4412-9835-87d27b904b8f.webm)
- Add border-radius to carousel images ;
- Add little padding to InkWell (to clearly see the effect) ;
- Center the InkWell to avoid full width with small image inside.
Fixes #247

Add border-radius to carousel images

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/updates/update_dialog.dart

Some updates send their whole changelog and not only the latest changes over packagekit
This can kill the markdown inside the updates dialog.
Thus this cuts the changelog after 4k chars for now and links to the website after

Updates: cut changelog after 4k chars

---

snap/snapcraft.yaml

Added layout to make amdgpu.ids available at the expected location, attempting to fix issue #267

Added layout to make amdgpu.ids available at the expected location

---

lib/store_app/common/offline_page.dart
pubspec.lock
pubspec.yaml

Fixes #336
Related to #233 #73

Reuse disabledColor for noNetwork animated icon

---

lib/store_app/store_app.dart

I added function that tries to resolve the current locale using the default functionality already present. Additionally it also checks if:
- the locale was the first in the list of supported locales,
- the locale is not present in the device locales.
If both checks pass, it returns the English locale instead.
Unfortunately I was not able to replicate the exact bug listed in #216, though I did test this on a couple of machines and it seemed to work. @AdamSzopa could you confirm if this fixes the issue on your end?
closes #216

fix: update localization default to english

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/main.dart
lib/services/package_service.dart
lib/store_app/common/confirmation_dialog.dart
lib/store_app/common/constants.dart
lib/store_app/settings/settings_model.dart
lib/store_app/settings/settings_page.dart
lib/store_app/updates/updates_page.dart

This removes the disabling of the window controls on update checking and updating.
Instead we hide the window by default on close. If the user wants to quit the app there is a new row in the settings page to do so.
If updates are currently running a confirmation dialogue will ask again if the user really wants to quit.
This hiding also has the advantage of preserving the 30 minutes update checker in the background. We need also a notification if updates are available but this can be done in a different PR.
Fixes #235

Prevent update interruptions more gracefully on app close

---

lib/main.dart
lib/store_app/updates/updates_model.dart
lib/store_app/updates/updates_page.dart
pubspec.lock
pubspec.yaml

The GNOME-specific SessionManager was renamed to GnomeSessionManager and a new simplified API was made available as UbuntuSession named after the package. Later on, the common UbuntuSession API will be implemented for a variety of flavors and desktops.

Upgrade ubuntu_session

---

lib/services/snap_service.dart
lib/store_app/common/snap_model.dart
test/services/snap_service_test.dart

Load snap authorization macaroon only once, when initializing the service.

---

lib/store_app/explore/search_field.dart

- make the icon use primary color to indicate that this icon is interactive to set the section filter

ExplorePage: filter field section icon color

---

lib/store_app/common/app_format_button.dart
lib/store_app/common/drop_down_decoration.dart
lib/store_app/common/snap_channel_button.dart
lib/store_app/common/snap_section_dropdown.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/search_field.dart
lib/store_app/explore/search_page.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/my_apps/my_snaps_page.dart

This moves the snap section filter dropdown out of the search bar into the search page.
This is also better for the future, when we might add more filters, that are dependant on the app format (snap/packagekit)
CC @anasereijo 
Ref #319

Move the snap filter to the search page

---

lib/store_app/common/packagekit_group_button.dart
lib/store_app/common/packagekit_group_utils.dart

Missing icons:
- gnome
- kde
- xfce
- collections
- repos
- communication
- legacy
- office
- documentation
CC @Jupi007

PackageKitGroupButton: add icons

---

lib/store_app/explore/explore_header.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/start_page.dart

- return the filterbar for all explore page states
- do not insert new scrollcontroller every time for the search pages
- align padding to match on all explore sub pages

ExplorePage: simpify hiearchy and return filter

---

lib/services/package_service.dart
lib/store_app/updates/updates_model.dart

Like lastUpdatesState we need all values relevant for the updates page to be initialized, no matter if a value is put into the stream or not.

PackageService and Updates model last values

---

lib/store_app/common/app_page/app_page.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/common/snap/snap_page.dart
lib/store_app/explore/explore_model.dart
lib/store_app/explore/explore_page.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner_grid.dart
lib/store_app/explore/start_page.dart
lib/store_app/my_apps/my_apps_model.dart
lib/store_app/my_apps/my_apps_page.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart

This ensures that the corresponding pages are not rebuilt when popping a details page (#444).

Do not track the currently displayed app/snap in the models (ExploreModel, MyAppsModel).

---

lib/store_app/common/app_page/app_reviews.dart

nested scrollviews do not work with wayland and trackpads

AppReviews: use column instead of listview

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/store_app/explore/search_page.dart

Fixes #474
Plus updates to the dialog:
- more space for buttons
- add a message what's happening
https://user-images.githubusercontent.com/15329494/199501811-3143df67-6cf7-4afb-910f-ad0147d0d8ea.mp4

Regression: app pages should not hide navigation

---

lib/store_app/common/app_page/app_header.dart
lib/store_app/common/app_page/app_page.dart
lib/store_app/common/snap/snap_connections_settings.dart
pubspec.yaml

- update yaru_widgets to 2.0.0-beta-1
- revert the fittedbox change to AppHeader for now
- exchange Switch with YaruSwitch
- adapt YaruCarouselController to yaru_widgets

Udapte yaru_widgets and revert FittedBox

---

lib/services/package_service.dart
lib/store_app/updates/updates_model.dart

- clean up event-type checking control block to only if or elf if blocks
- only set update state to updating in progress events
- check if the transaction has been canceled
- only clean up updates and stream controllers if the process has not been cancelled
- create sets of events that should be ignored to not report every error to the model and thus the view
- only use ubuntu session commands to control logout/reboot
Ref #503
Ref #488

Improve PackageService updateAll

---

lib/store_app/common/packagekit/package_page.dart

Makes permissionContainer null to make it work with the if statement clause. Removes additional padding.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
Fixes #512

Remove extra padding between Description and Review containers

---

pubspec.yaml

Just require `yaru_icons: 0.2.7` to get the patch.
The visual diff is very very soft, so sorry but no screenshot :D
Fixes #528

Require specific 0.2.7 version of yaru_icons

---

lib/store_app/common/app_icon.dart
lib/store_app/common/packagekit/package_page.dart
lib/store_app/common/snap/snap_page.dart
lib/store_app/explore/color_banner.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_banner.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/updates/update_dialog.dart

AppIcon: use an app format agnostic fallback icon

---

lib/store_app/common/app_icon.dart
lib/store_app/common/border_container.dart
lib/store_app/explore/section_banner.dart

- add optional border color to border container
- set it to be visible on the white base plate of the app icons in the section banner
- animate the base plate on hover

AppIcon refinements for the sectionbanner

---

lib/store_app/common/app_page/page_layouts.dart
lib/store_app/common/constants.dart
lib/store_app/explore/explore_header.dart
lib/store_app/explore/section_banner.dart

Hey sorry, I tried to rebase the last pull request but something seems to have gone horribly wrong.
Like the last PR, this makes all of the padding in the explore page 25px. 
As for the apps page, I thought that it would look better if the entire page was centred in addition to it changing back to a single page view once the padding on the left and right equal 20 (or kPagePadding). This still conforms to the ultra-wide monitors aspect-ratio.
before:
https://user-images.githubusercontent.com/73116038/203015107-3658f93c-710a-46be-ab08-fbbeaa8789f8.mp4
after:
https://user-images.githubusercontent.com/73116038/203015092-43b9f1ba-0c7c-4248-b6f6-59871acf2df7.mp4
What do you think? @Feichtmeier 
Fixes #534

Small padding adjustements - Center the apps page

---

lib/store_app/explore/color_banner.dart
lib/store_app/explore/search_page.dart

The same can be done with a `Column` as a subtitle. This is marginally more code here but helps us to generalize the `YaruBanner` layout.

Migrate away from YaruBanner.thirdTitle

---

lib/store_app/common/app_page/app_page.dart
lib/store_app/common/loading_banner_grid.dart
lib/store_app/explore/color_banner.dart
lib/store_app/explore/search_page.dart
lib/store_app/explore/section_grid.dart
lib/store_app/my_apps/my_packages_page.dart
lib/store_app/my_apps/my_snaps_page.dart
lib/store_app/store_app.dart
pubspec.yaml

Reverts ubuntu-flutter-community/software#596
- wrong bg color of yaru banners
- stretched app icons
- overflowing third title
Sorry @jpnurmi I should have checked out and tested. Can you try again or would this be more effort than to just create a PR with fixes?

Revert "Adapt to latest yaru_widgets changes"

---

lib/store_app/explore/explore_model.dart

Band-aid fix for 22.10: disable appstream search by default

---

lib/store_app/explore/explore_page.dart

This fixes the issue that the whole ExplorePage was built ~20 times on startup. ExplorePage doesn't care about all the snap-related changes that ExploreModel notifies of most of the time.
Ref: #609

ExplorePage: use select() to avoid excessive rebuilds

---

lib/store_app/explore/section_grid.dart

On startup, the section grid view item builder gets now called once for each item, so 27 times. Before the select() changes, it was called 21x27=567 times.
Ref: #609

SectionGrid: use select() to optimize rebuilds

---

lib/app/app.dart

Otherwise the app is rebuild from the very start on every build (it always returns to explore page and then re-renders 3-5 times)
@d-loose was the key important for the packageinstaller page?

app: do not add a global key

---

snap/snapcraft.yaml

Added network-manager plug, not needed to autoconnect but necessary for systems running network-manager as a snap.  Fixes #620

Added network-manager plug

---

lib/app/common/snap/snap_connections_settings.dart

Ref use `context.select()` instead of `context.watch()` #609

SnapConnections: use context.select

---

lib/app/common/app_format_popup.dart
lib/app/explore/explore_header.dart
lib/app/explore/explore_model.dart
lib/app/explore/search_page.dart
lib/app/installed/installed_header.dart
lib/app/installed/installed_model.dart
lib/app/installed/installed_packages_page.dart
lib/app/installed/installed_page.dart
lib/app/installed/installed_snaps_page.dart
lib/app/settings/settings_model.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart
lib/services/packagekit/package_service.dart
pubspec.yaml

- catch `DBusServiceUnknownException` on `_client.connect()`
(introduces `dbus` dependency, until `PackageKitClient` gets its own exception)
- add an `isAvailable` property to `PackageService`
- hide packageKit specific UI elements if the service isn't available
fix #620

Handle absence of PackageKit more gracefully in the UI

---

pubspec.yaml

The integration test crashes in the CI. Presumably, due to https://github.com/leanflutter/window_manager/pull/268.

Pin window_manager at 0.2.8

---

lib/app/explore/explore_model.dart
lib/app/explore/search_page.dart
lib/services/snap_service.dart

* add `AppFormat.packageKit` to enabled and selected formats after `AppStreamService` is done with its initialization
* only subscribe to  `SnapService.sectionsChanged` in `ExploreModel` after `SnapService` is done with its initalization (reduces early page rebuilds)
https://user-images.githubusercontent.com/113362648/210390478-5936c552-d632-41bd-9711-ef6e19c53393.mp4
Any suggestions on how to indicate that `AppStreamService` is still loading in the background?
ref #663

Improve Search/Explore page initialization

---

lib/app/common/app_page/page_layouts.dart
lib/app/common/constants.dart
lib/app/explore/explore_header.dart
lib/app/explore/search_page.dart
lib/app/explore/section_banner.dart
lib/app/explore/section_grid.dart
lib/app/updates/package_updates_page.dart
lib/app/updates/snap_updates_page.dart

Just gathering feedback to see if this look is preferred over the older one. The padding here is 20px visually for consistency. I still need to cleanup some widgets which don't make use the available constants.
https://user-images.githubusercontent.com/73116038/210177948-1c05a49c-333e-474f-908a-8b21c741b47c.mp4
The only issue I could see being introduced here is the fact that a Yaru banner that is currently hovered on will look slightly out of place because the border is now shown. Though IMO this is a trade-off that is worth it given that everything now looks properly aligned.
Fixes #676

Make padding 20px (visually) throughout the application

---

lib/app/explore/explore_model.dart
lib/app/explore/search_page.dart

Restore incremental loading of snap sections (revert part of #683) and instead rebuild `SearchPage` only if the search parameters change.
https://user-images.githubusercontent.com/113362648/210746328-518394a7-5088-4a5c-b2d5-6830ebc4e97a.mp4
Fix #663

SearchPage: rebuild only when necessary

---

integration_test/software_test.dart
lib/app/app.dart

* Use `pumpUntil` to make sure a `PackagePage` is rendered, before trying to find any widgets or accessing localization strings through a build context.
I've tried adding some delays in various init methods to try and recreate a situation where we end up not having a `PackagePage` and a proper build context after awaiting `pumpAndSettle` (which is likely the cause of the last failure in the CI), but without success. In any case, using `pumpUntil` should make sure this never happens :crossed_fingers: 
Thanks @jpnurmi!

another integration test fix (hopefully the last one)

---

lib/app/explore/explore_model.dart
lib/services/packagekit/package_service.dart

This makes sure debian packages are added as an option to the dropdown once `PackageService` is loaded, if packagekit is available
fix #663

ExplorePage: ensure PackageService is initialized

---

lib/app/common/app_banner.dart

Before:
After:
@madsrh What do you think about making the description completely white in dark mode to match it to the title colour? Added some screenshots :)
fixes #702

Make text black in light mode and white in dark mode

---

lib/app/common/updates_splash_screen.dart
lib/app/installed/installed_snaps_page.dart
lib/app/updates/no_updates_page.dart
lib/app/updates/package_updates_page.dart
lib/app/updates/snap_updates_page.dart

- do not hide expanded widget since the usage varies
- make the splash and no updates pages scrollable for very narrow heights (600-700)
https://user-images.githubusercontent.com/15329494/211192096-901dd1ad-56b8-40ab-a4d9-dbb83740e2fd.mp4
Fixes #715

Updated related pages fixes

---

lib/app/explore/explore_header.dart
lib/app/explore/explore_model.dart

Use `context.select` in `ExploreHeader` to reduce unnecessary rebuilds.
Ref #609

ExploreHeader: use context.select

---

lib/app/explore/start_page.dart
lib/app/updates/snap_updates_page.dart

Exceptions are induced because the snap list is empty. By returning another page instead of the SnapGrid when there are no snaps to update, the exceptions go away.
https://user-images.githubusercontent.com/73116038/211387089-279a179d-4b10-4cbd-9421-5b99d8132926.mp4
Fixes #719

Fix update page exceptions

---

.github/workflows/build.yml
.github/workflows/test.yml
integration_test/assets/network-manager-ci.pkla
integration_test/assets/snapd-ci.pkla
integration_test/software_test.dart

A first step towards a better integration test.
* add a new test that installs and removes the [GNU hello snap](https://snapcraft.io/hello)
* break down tests into smaller pieces with minimal UI/UX assumptions:
- install package
* expect file installed by package is not present
* expect to find no enabled `OutlinedButton` with label `Remove`
* expect to find a single enabled `ElevatedButton` with label 'Install' and tap it
* wait until an enabled `OutlinedButton` with label 'Remove' is found
* expect no enabled `ElevatedButton` with label 'Install' is found
* expect file installed by package is present
- remove package
* expect file installed by package not present
* expect to find no enabled `ElevatedButton` with label `Install`
* expect to find a single enabled `OutlinedButton` with …

Improve integration test

---

lib/app/app.dart
lib/app/common/app_page/app_page.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/search_field.dart
lib/app/common/snap/snap_grid.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart
lib/main.dart
pubspec.yaml

- use yaruwindowtitlebar to save vertical screenspace
- adapt the layout to use yarumasterdetailpage
- add the searchbar to the titlebar
- adapt all pages containing an appbar to use yaruwindowtitlebar

YaruWindowTitlebar: big layout changes

---

lib/app/common/app_page/app_reviews.dart
lib/app/common/message_bar.dart
lib/app/common/packagekit/package_page.dart
lib/app/settings/repo_dialog.dart
lib/app/updates/update_dialog.dart

This is a  needed fix for the api change of titlebars in yaru widgets to make the **close button** in dialogs return

Fix API change: Bring back dialog close buttons

---

lib/app/updates/update_dialog.dart

UpdateDialog: remove leading fallback icon and center title

---

lib/app/app.dart
lib/app/common/search_field.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart
lib/app/installed/installed_page.dart
lib/app/settings/settings_page.dart
lib/app/updates/updates_page.dart
pubspec.yaml

The client side decorations make this app feel much more at home in Ubuntu with GNOME.
However the master detail navigation currently needs a bit more refinement in yaru_widgets, since #766 occurred for some but most importantly this bug
#761.
This reverts the navigation back to how it was but keeps the CSD to make this app feel at home on Ubuntu desktop.
Closes #766 
Closes #761 
But we should re-open those bugs if not present in yaru_widgets
Screenshots 
Recording for the transition animations:
https://user-images.githubusercontent.com/15329494/212465362-4dadf7fd-d5b8-4c12-8f33-80a97bfe4e41.mp4

Revert navigation but keep CSD

---

pubspec.yaml

If we keep the "release" from pubspec as the version in snap-store, we need to figure out a different way to create releases to not create merge conflicts. We could leave out the version in pubspec to be "alpha" and then change the version only for the merge into the other channel to be "0.2....." with a number.
Anyway, keeping the previous release procedure for now until we figured this all out.

Release 0.2.6-alpha

---

lib/app/common/packagekit/package_controls.dart
lib/l10n/app_en.arb

https://user-images.githubusercontent.com/113362648/212661280-9c1232e7-3c10-4b55-ae9e-9ba2736e737f.mp4
Currently `PackageState` has only two states (`processing` and `ready`) - we should probably add more specific states in the future.
fix #783

Show progress indicator when installing/removing deb packages

---

lib/app/common/app_banner.dart
lib/app/common/app_icon.dart
lib/app/common/app_page/app_page.dart
lib/app/common/base_plate.dart

- use a rounded square form to avoid clipping for hard edge square forms, i.e. to avoid this:
- adjust padding to make them look bigger when they are very small
- always make the fallback icon light to avoid bulls-eye effect, to be clear, to avoid this:
- adjust fallback icon borders
After (dark):
After (light):

BasePlate and FallBackIcon improvements

---

lib/app/common/loading_banner_grid.dart
lib/app/explore/explore_error_page.dart
lib/app/explore/explore_page.dart
lib/app/explore/search_page.dart
lib/app/explore/start_page.dart

Bonus: adapted the loading grid to include a fake explore header
https://user-images.githubusercontent.com/15329494/213189875-40a2046a-435d-4d4c-b187-a56d215cb10a.mp4
Fixes #814

move the `Scaffold` with the `SearchField` to `ExplorePage`

---

lib/app/common/search_field.dart
lib/app/explore/search_page.dart

* fix `SearchPage` rebuilds
* add 200ms grace period to `SearchField` (i.e. start search only 200ms after the user stops typing)
Before
https://user-images.githubusercontent.com/113362648/213253723-234088db-2111-4d82-bdbe-8ee533249fd5.mp4
After
https://user-images.githubusercontent.com/113362648/213253787-16148abd-9558-47ce-a6a3-793da477ef5b.mp4

Search page optimization

---

lib/app/common/app_icon.dart

Info: they were removed because we tried the white baseplate, which we reverted but I have forgotten to revert the appicon fallback icon for the dark theme
https://user-images.githubusercontent.com/15329494/213312047-420df927-794c-46f0-91c2-1b3e7406e94b.mp4
Fixes #817

Bring back dark AppIcon loading icon without a baseplate

---

lib/app/common/app_icon.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/border_container.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart
lib/app/updates/package_updates_page.dart

BorderContainer: use YaruBorderContainer
No visual differences but this makes it a little easier to track properties and maintain the code.
Replacing all occurences of BorderContainer with YaruBordercontainer would also work but it would generate more lines of diff since the defaults for 90% of the constructor calls for software are defaulted in bordercontainer

BorderContainer: use YaruBorderContainer

---

lib/app/app.dart
lib/app/app_model.dart
lib/main.dart
pubspec.yaml
snap/snapcraft.yaml
test/widget_test.dart

https://user-images.githubusercontent.com/113362648/214027558-5e0e5424-fa7c-4a24-b73f-58affd57f551.mp4
It would be nice to show an overall percentage somehow, but for now all we have is the percentage that `PackageKitItemProgressEvent` provides.
fix #687

Show number of available updates and progress in launcher icon

---

lib/app/common/app_icon.dart
lib/app/common/app_page/app_header.dart
pubspec.yaml

I used a `FittedBox`, so the icon scale to the parent `SizedBox`.
Fixes #798

Use new fallback icon

---

lib/app/common/app_banner.dart
lib/app/common/app_icon.dart
lib/app/common/constants.dart
lib/app/common/safe_network_image.dart
lib/app/common/snap/snap_section.dart
lib/snapx.dart

Adds AppImageBanner without using it. **No visual changes**
Included are some additions to constants to not duplicate too much code.
If we want to re-use it we could do so by for example:
```dart
final sectionSnapsGames = context.select((ExploreModel m) {
return m.sectionNameToSnapsMap[SnapSection.games];
});
....
GridView(
shrinkWrap: true,
padding: kGridPadding,
physics: const NeverScrollableScrollPhysics(),
gridDelegate: kImageGridDelegate,
children: [
for (final snap in sectionSnapsGames
?.where((s) => s.bannerUrl != null)
.toList() ??
<Snap>[])
AppImageBanner(snap: snap),
],
)
```

Add image banner without using it

---

lib/app/common/app_banner.dart
lib/app/common/app_icon.dart
lib/app/explore/section_banner.dart

- Avoid overflow and make sure the hand pointer cursor always shows up
- [Re-add brightness agnostic highlights to appicon](https://github.com/ubuntu-flutter-community/software/pull/866/commits/0352c4ad3448d5c7c61905bba95b80c0c0a4264a)
(still not added to the app visibly!)

AppImageBanner: fixes

---

lib/app/installed/installed_page.dart
lib/app/updates/updates_page.dart

This is a temporary solution to allow step-by-step migration. We might eventually want to port to the new official [Badge](https://api.flutter.dev/flutter/material/Badge-class.html).

Namespace badges.dart to avoid conflict with Badge in Flutter 3.7.0

---

lib/app/updates/package_updates_model.dart
lib/app/updates/package_updates_page.dart
pubspec.yaml

LogView is compatible with Flutter 3.7.0 but also lighter because it's just a plain read-only TextField under the hood.
|---|---|
| ![Screenshot from 2023-01-26 11-37-10](https://user-images.githubusercontent.com/140617/214818467-382d6a55-3bea-49d2-a18a-4ef2cd46f687.png) | ![Screenshot from 2023-01-26 11-50-59](https://user-images.githubusercontent.com/140617/214818490-b1855861-eca8-40ae-b7d8-1428e9657958.png) |

Replace xterm with LogView from ufp/ubuntu_widgets

---

lib/app/common/search_field.dart

Fixes regression, clear icon is back now if the field is not empty
Fixes #801

Add clear icon to searchbar

---

lib/app/app.dart
lib/app/app_model.dart
lib/app/common/connectivity_notifier.dart
lib/app/explore/explore_page.dart
test/connectivity_test.dart

The connectivity status is not needed in AppModel. Having it in a small separate unit that only notifies connectivity status changes makes it cheap to watch anywhere connectivity status is needed. At the moment, the only place that needs the connectivity status is ExplorePage.
[connectivity.webm](https://user-images.githubusercontent.com/140617/215121727-58147503-43b9-4cc2-8d12-e9e77ecb1864.webm)

Move connectivity from AppModel into a small standalone unit

---

lib/app/updates/update_dialog.dart

Continuing #902
- Selectable text
- Bold text for package detail labels
- Removed padding
- Moved expander arrow to start
- Reordered list of details so website is at bottom

More styling fixes

---

lib/app/common/app_banner.dart
lib/app/common/app_data.dart
lib/app/common/app_page/app_header.dart
lib/app/common/app_page/app_infos/additional_information.dart
lib/app/common/app_page/app_infos/app_infos.dart
lib/app/common/app_page/app_infos/links_info_fragment.dart
lib/app/common/link.dart
lib/app/common/packagekit/package_model.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_page.dart
lib/app/updates/update_dialog.dart
pubspec.yaml
test/services/package_service_test.dart

- appstream uses kind of random locale strings
- in package page we also have the package id that can be used for the license :+1: 
- appstream sometimes has released at info, fallback to unkown as discussed with the other designers :+1: 
- reliable language tags are "C" (haha so funny 90s geeks), "en_GB" and "en"
- fallback in appbanner is the name, since most of the publisher names would be "UNKNOWN" otherwise which looks really weird here
- released at needs improvements in terms of formatting, in a second PR after this
- changed most of the model getters to return nullable types, to correctly digest this in the UI, we should do this in a different PR for more getters, they should all be null if they could be null and we should never return default values in models anymore like '' or …

AppBanner & PackagePage: fill all infos with data or fallback string

---

pubspec.yaml

Fixes a visual regression of appbanners being grey in the light theme, introduced by me in yaru.dart 0.5.0 and fixed by me in 0.5.1
|before|after|
|-|-|
|![grafik](https://user-images.githubusercontent.com/15329494/215490640-904c22dd-65cd-44da-bea0-25b814aafbe8.png)|![grafik](https://user-images.githubusercontent.com/15329494/215490520-9fb339dc-71e7-4523-9b1f-c61edd388129.png)|
Fixes #907

AppBanners: bring back correct BG colour in the light theme

---

lib/app/common/packagekit/package_page.dart

Very small improvements towards #739
- moved expander to start
- removed text changing (feels weird that the text changes when expanded)
- added border
As you can see there's still some issues. Just a placeholder until some advanced help (not me) arrives implementing [this idea 🖼️  ](https://github.com/ubuntu-flutter-community/software/issues/739#issuecomment-1399258699)

Small styling fixes for dependecies popup

---

integration_test/software_test.dart
lib/app/common/search_field.dart
lib/app/explore/explore_page.dart
lib/app/installed/installed_page.dart
lib/l10n/app_en.arb

- adds search hints for explore and installed as decided with the other designers
- use a custom close button to avoid height jumping as suffix icon
Fixes #854

Improve search hint and avoid height jumping

---

lib/app/app.dart
lib/app/common/app_banner.dart
lib/app/common/app_finding.dart
lib/app/common/app_rating.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/rating_model.dart
lib/app/common/snap/snap_grid.dart
lib/app/common/snap/snap_page.dart
lib/app/explore/explore_model.dart
lib/app/explore/section_grid.dart

Decouple app data and associated ratings because the latter comes from a different (potentially slow and unreliable) data source. We must be able to present apps in the GUI without waiting for ratings to arrive.
Ref: #872

Refactor: separate app data and ratings

---

snap/snapcraft.yaml

We're specifying `source-tag: 3.3.10` but then executing `flutter channel stable` followed by `flutter upgrade` which means we're actually using the very latest stable release.
Yaru and friends required 3.7.0 these days, so use that because our arm64 build is currently broken, which could be related to 3.7.1?
```
: [        ] [  +23 ms] Target release_bundle_linux-arm64_assets failed: ShaderCompilerException: Shader compilation of "/build/snap-store/parts/flutter-git/install/usr/libexec/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag" to "/build/snap-store/parts/software/build/build/flutter_assets/shaders/ink_sparkle.frag" failed with exit code 1.
:: [        ]            impellerc stdout:
:: [        ]            impellerc stderr:
:: [        ]            Compilation …
```

snap: use flutter 3.7.0

---

lib/app/app.dart
lib/app/settings/repo_dialog.dart
lib/app/settings/settings_page.dart

I think it would be better to open the settings page without the need to leave the current page.
Any veto @anasereijo @madsrh @Jupi007 @d-loose  or @jpnurmi ? :smile_cat: 
Edit: if we merge this I will change the other dialogs on this page to be inside the settings dialog instead of opening a new one

Settings: move to trailing & open in dialog

---

lib/app/common/app_page/app_header.dart

Use the same font weight as expander headlines. Not sure if using bold font here is the correct solution. WDYT? @Feichtmeier @Jupi007 
Fixes https://github.com/ubuntu-flutter-community/software/issues/962 
Also slightly smaller fontsize for the publishername.

Changed font size for app_header

---

lib/app/settings/settings_page.dart

Small tweaks for license page:
- Removed duplicate back button
- Use full window height (removed SizedBox)
Before:
After:

LicensePage tweaks

---

lib/services/packagekit/package_service.dart
test/services/package_service_test.dart

Uninstalled packages need to be included in the search to correctly determine whether a package is installed - otherwise it will find installed packages with a similar name, e.g. leftover dependencies like [packagename]-data.
Fix #976

PackageService: remove filter in isInstalled

---

lib/services/packagekit/package_service.dart

Sorry, this needs another fix:
with multiple matches it reports the 'installed' status of the last package event, even if the name doesn't match.

PackageService: fix isInstalled

---

lib/app/collection/collection_model.dart
lib/app/collection/collection_page.dart
lib/app/collection/package_update_banner.dart
lib/app/collection/package_updates_page.dart

- removed "collection" prefix in files and classes where it does not make sense
- re-add all debian package related controls (refresh, update all)
- adapt the deb updates section to snap updates
- adapt deb updates list to installed deb list
- move PackageUpdatesModel higher in the tree to a multiprovider around collectionpage
- do not always ask packageService for a fresh list of updates on page refresh, stream subs should update the page here
- do not show all debian packages but only     PackageKitFilter.installed,
PackageKitFilter.gui,
PackageKitFilter.newest,
PackageKitFilter.application,
PackageKitFilter.notSource,
PackageKitFilter.notDevelopment,
NOTE: this needs a change in yaru widgets to have the button have a padding without having the whole expandable have a padding …

CollectionPage: re-add deb controls and improve layout

---

lib/app/collection/collection_model.dart

Was abs. not needed. It's null on start that is correct :+1: 
Afterwards the service takes care

CollectionModel: remove unecessary list clearing

---

lib/services/packagekit/package_service.dart

only send one packages changed signal after the transaction completes,
instead of sending one for each packagekit event

PackageService: reduce signals in getInstalledPackages

---

lib/app/common/app_page/app_infos/additional_information.dart

Shows all of the items in the additional information section.
After:
https://user-images.githubusercontent.com/73116038/217977554-67cc4b2a-9a72-4cd6-b3e7-173846a4676f.mp4
Fixes #1019

show all items in Additional Information section

---

lib/app/common/app_page/app_infos/app_infos.dart
lib/app/common/app_page/app_infos/app_size_fragment.dart
lib/app/common/app_page/app_infos/confinment_info_fragment.dart
lib/app/common/app_page/app_infos/install_date_info_fragment.dart
lib/app/common/app_page/app_infos/license_info_fragment.dart
lib/app/common/app_page/app_infos/publisher_info_fragment.dart
lib/app/common/app_page/app_infos/released_at_info_fragment.dart
lib/app/common/app_page/app_infos/version_info_fragment.dart

@Feichtmeier @local-optimum @Jupi007 continuing to explore a solution to  [#887](https://github.com/ubuntu-flutter-community/software/issues/887) on how to avoid redundant information, could this solution work?
- removed unnecessary tooltips
- added a length threshold for Version and Publisher

Remove unnecessary toolips

---

lib/app/common/app_page/app_format_toggle_buttons.dart
lib/app/common/packagekit/package_page.dart
lib/app/common/snap/snap_controls.dart
lib/app/common/snap/snap_page.dart
pubspec.yaml

Snap and Deb available:
Only snap but with multiple channels:
Only 1 channel and only snap:
Fixes #1036

Package type visualization improvements

---

lib/app/common/snap/snap_channel_button.dart

When I tried https://github.com/ubuntu-flutter-community/software/pull/1040 I noticed missing padding in the dropdown
Before:
This PR:

Added padding to snapchannel popup button

---

lib/app/common/snap/snap_controls.dart
lib/app/common/snap/snap_model.dart
lib/app/common/snap/snap_page.dart
lib/app/common/snap/snap_utils.dart

It turns out that the issue was something totally different. I didn't check if the selected channel version is null.
Which I did now and then there is no version to compare to which means that there is no update available.
I first ran `snap refresh kde...." in the terminal and snapd said that there is no update available. After that I found the bug in the code
Fixes #1042

Correctly look for snap updates

---

.github/workflows/cla-check.yaml

This reverts commit fe060388bc8bced4d9432cabb4f65d595ca4021c.
Sorry, this doesn't work - the username weblate uses does not end in '[bot]'.
See https://github.com/canonical/has-signed-canonical-cla/blob/main/index.js#L63

Revert "exempt common bots from CLA (#1053)"

---

linux/CMakeLists.txt
linux/my_application.cc
pubspec_overrides.yaml

- Use `HdyWindow` directly from libhandy instead of relying on the widget tree restructuring magic by `handy_window`
- Restore the original order for showing the window and view, as it is in the Flutter app template
Probably fixes: #868

Attempt to fix occasional blank window

---

lib/app/collection/collection_model.dart
lib/app/common/snap/snap_model.dart
lib/app/common/snap/snap_utils.dart
lib/services/snap_service.dart
pubspec.yaml
test/services/snap_service_test.dart

Removes some client side logic that is no longer needed.
Fixes #1062

Use snapd.dart to find snaps with updates

---

lib/app/explore/explore_model.dart

CC @local-optimum 
The steam snap is unlisted. So now show it if you type in the exact name
But not if by any query
Though you should prbly set the steam snap to listed at some point :)

Find unlisted snaps by exact name

---

pubspec_overrides.yaml

No longer needed with `yaru_window`.

Remove `pubspec_overrides.yaml`

---

lib/app/collection/package_updates_page.dart
lib/app/common/app_page/app_description.dart
lib/app/common/app_page/app_infos/additional_information.dart
lib/app/common/app_page/app_page.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/expandable_title.dart
lib/app/common/packagekit/package_page.dart

@anasereijo mentioned making the expander titles a bit smaller. It quickly became a mess, so @Jupi007 suggested creating a YaruExpandableTitle widget. 
Current master:
PR:
Updates:

Smaller fontsize for YaruExpanders

---

lib/app/common/app_page/app_header.dart

Removed _scaledFontSize_ and set _titleLarge_ at size 23. In the issue screenshots I used font-size 24, but had an overflow issue with special characters.
Fixes #1088 
I've removed the eclipses for the layout where there's plenty of space.

Fixed apppage title size

---

lib/app/common/snap/snap_channel_button.dart

Some cleanup 🧹 IMHO much easier to read.
- slightly darker grey using the hint color.
- the font size was already 14
- normal font weight is easier to read

Snap channel dropdown text styling

---

lib/app/common/packagekit/package_page.dart

Don't change color when expanded. From design mockup here: https://github.com/ubuntu-flutter-community/software/issues/739#issuecomment-1379080564
@anasereijo ?

Dependency expander text color

---

lib/app/collection/package_update_dialog.dart
lib/app/common/app_page/app_description.dart
lib/app/settings/settings_page.dart

Use primary color for links in apppage _description_ and update _changelog_
Before / After:

Use primary color for links

---

pubspec.yaml

A request from the installer team led to stronger borders and to popupmenu buttons (dropdowns) having the same border as outlined buttons
| - | - |
|![grafik](https://user-images.githubusercontent.com/15329494/220879719-0929aba9-f5e8-4390-9198-d1309f570a1f.png)|![grafik](https://user-images.githubusercontent.com/15329494/220879081-d6566d07-cf2e-4c0c-847d-b27735e9fd6d.png)|
|![grafik](https://user-images.githubusercontent.com/15329494/220879754-260643ab-23a1-4db1-b4e3-436349d6de95.png)|![grafik](https://user-images.githubusercontent.com/15329494/220879175-a8bebc89-2b79-49c3-aecd-a7e3c93c236d.png)|
Updating yaru and yaru_widgets here will thus also change those styles here.
Is this okay for you @anasereijo @Zoospora @madsrh ?

Update from yaru

---

lib/app/common/app_page/app_reviews.dart
lib/l10n/app_en.arb

Small fixes: 
- added translations
- pointer cursor on stars
- text sizes
- color for 👍 👎 (looked disabled)
- removed label "Rating:"
- aligned textfield hint-text to top
- padding on iconbuttons
There is still some issues that I couldn't figure out, which is if the translation for _report abuse_ is really long it creates overflow. And adding a FAB button 🔼 to the long list of reviews.

Review styling

---

lib/app/collection/collection_model.dart
lib/services/snap_service.dart

Since https://github.com/ubuntu-flutter-community/software/pull/1105 would hide update information of the individual snaps, let's instead keep the current mechanism where we refresh each snap individually and solve the auth dialog issue by checking for an exception.
Fix #1074

Cancel `refreshAll` if first PolKit authentication request is cancelled

---

lib/app/common/packagekit/package_page.dart

For something like _Inkscape_ where there are 149 dependencies, it takes forever to scroll to the total size a the bottom, so I've added the size to the expander title. Maybe it's too much info 🤷‍♂️ 
Piggybacking on the work by @d-loose I've added summary to dialog + color tweaks for summary text and icon.

Dependencies styling

---

lib/app/collection/simple_snap_controls.dart
lib/app/collection/simple_snap_model.dart
lib/main.dart
pubspec.yaml
snap/snapcraft.yaml

Uses [snapcraft_launcher.dart](https://github.com/d-loose/snapcraft_launcher.dart) to launch desktop applications from other snaps.
Fix #209

use desktop launch interface

---

lib/app/collection/package_update_dialog.dart
lib/app/common/app_page/app_description.dart
lib/app/common/app_page/app_page.dart
lib/app/common/link.dart
lib/app/settings/settings_page.dart

Continuing https://github.com/ubuntu-flutter-community/software/pull/1094/files because of the installer using blue links https://github.com/canonical/ubuntu-desktop-installer/pull/1486 and also ofc the Vanilla framework, here's the return of the blue links.
This sounded like low hanging fruit, but got more advanced than I had anticipated, so there might be a better way of doing this 🤷‍♂️

Linkcolor blue - again

---

lib/app/common/app_banner.dart
lib/app/common/app_page/publisher_name.dart

Just a suggestion: a very small change, but I think this is easier to read. WDYT? @anasereijo @Jupi007 @Feichtmeier 
- removed _italic_
- used Hintcolor
I wonder if we should remove the italic from the app page also?

More readable publisherName for app_banners

---

lib/app/common/app_format_popup.dart

The two dropdowns or popups should have the same font size:

Appformat popup font size

---

lib/app/common/app_page/app_reviews.dart

Removes unnecessary space between the review carousel and the "show all reviews" button.
Before:
After:

removed unnecessary sized box

---

lib/app/settings/theme_tile.dart

You can see the white container bleed through due to anti-aliasing in dark mode.
Before:
After:

Remove themeTile artifacts

---

lib/app/common/app_page/app_swipe_gesture.dart

Anytime the user would "restart" the gesture before the previous one had concluded, the position of the indicator would be left offscreen. This meant that the new gesture would be in action even though nothing was shown on screen. This PR fixes that :D
Before:
https://user-images.githubusercontent.com/73116038/225236598-de836d60-5061-4284-81c7-9bb718cffaf1.mp4
After:
https://user-images.githubusercontent.com/73116038/225236612-beafe821-4fef-4c05-b6d8-3beafde57ae6.mp4

Fix swipe animation not resetting

---

lib/app/common/snap/snap_model.dart

Here's another "death by a thousand paper cuts" fix 😅 Use the same date format for installed and released at date.
I would like to do something (UK/Eur) like `DateFormat('d. MMMM, y')` but that format isn't predefined, so I'm worried that localization won't work 🤷‍♂️
**Before**
**After**

Use same dateformat for ReleasedAt and InstalledAt

---

.github/workflows/test.yml
integration_test/assets/10-network-manager.yaml

Use a config file to use NetworkManager as the default renderer for netplan.
Setting the renderer via the CLI seems to not work anymore. 
Close #1223

Integration test: fix netplan

---

pubspec.yaml

Switch to a newly published version to have control over updates and protect against potentially breaking changes.
Includes a fix to set `content-type: application/json` header which may help with occasionally missing app reviews:
- https://github.com/ubuntu-flutter-community/odrs.dart/pull/5

chore(deps): odrs ^0.0.1

---

lib/app/explore/explore_model.dart

If multiple appstream components belong to the same package, prefer the one that has type 'desktop-application' in
`_getAppstreamComponentFromSnap`.
[Screencast from 2023-05-25 14-53-12.webm](https://github.com/ubuntu-flutter-community/software/assets/113362648/a993c74e-c084-48c8-9573-b96e1da02752)
Fix #1210

fix(explore): prefer desktop appstream components

---

lib/app/collection/collection_model.dart
lib/app/collection/snap_collection.dart
lib/services/snap_service.dart

- let the installed snaps load as fast as possible in the UI then load the updates after
- forward the list from the service to the model, what was the reason for this unmodifyable list here @d-loose ? No critique, just curious
- make the list nullable, which gives one more state and does not leave the user with the "no snaps installed" message for some seconds while the list is loading
- to not disable the not-updates-rows while checking for updates, I see no reason why
Fixes #1219
[Bildschirmaufzeichnung vom 2023-05-30, 20-11-47.webm](https://github.com/ubuntu-flutter-community/software/assets/15329494/0701b6d6-990b-40c8-a489-779525cd2165)

fix: Installed snap list taking long to load

---

lib/app/common/app_banner.dart
lib/app/common/app_icon.dart
pubspec.yaml

[`cached_network_image`](https://pub.dev/packages/cached_network_image) makes it possible to cache app icons and banners so that the images are not fetched from their url every time, making image loading faster.
Close #1116

Use cached_netowork_image for app banners and icons

---

lib/app/common/app_page/app_reviews.dart

There was an interactive rating bar outside the review dialog. This is not possible with ODRS because a rating can only be [submitted](https://github.com/GNOME/odrs-web/blob/51cc0b55cba833ca0f37209f339ea31f87906e72/odrs/views_api.py#L93) as part of a review. Also, re-submitting a review to ODRS is not possible (throws an "already reviewed" error).
If the user already has submitted a review, it is shown _without_ voting or reporting buttons and regardless of whether the app is currently installed.
The review button is shown only if the app is installed but not reviewed.
When the app is neither installed nor reviewed, neither above is shown.
Close: #1251

refactor(review): remove interactive rating bar

---

lib/app/common/app_page/app_page.dart
lib/app/common/app_page/app_reviews.dart
lib/app/common/app_page/review_sort_by.dart
lib/l10n/app_en.arb

@jpnurmi to keep the app page and its children independent of any models I've moved the state just to the dialog itself. In this case this should be okay since the sorting is not something to persist (yet?).
If the other designers want the sorting to be also inside the main page, I could create a separate state for this there
[Bildschirmaufzeichnung vom 2023-06-16, 13-58-42.webm](https://github.com/ubuntu-flutter-community/software/assets/15329494/e5a75b9f-f220-4755-9521-86974e593992)
Fixes #1177

reviews: filter dropdown missing from the 'show all reviews' dropdown

---

lib/app/common/app_page/app_reviews.dart
pubspec.yaml

Close #1181
Switched to [flutter_pannable_rating_bar](https://pub.dev/packages/flutter_pannable_rating_bar) for the app_reviews. The rating bars that serve as rating indicators (`ignoreGestures: true`) were left untouched.
flutter_pannable_rating_bar does not support colors with opacity for the unselected star icons at the moment so I had to hardcode the color values based on the app theme.

feat: add hover state to review stars

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
lib/src/search/search_provider.dart
lib/src/snapd/snap_provider.dart
test/detail_page_test.dart
test/test_utils.mocks.dart

UDENG-796
- adds `refreshProvider` which provides list of refreshable snaps
- adds a corresponding button to the detail page if the snap is refreshable
- UI questions to figure out:
* priority of action buttons; which ones will be hidden in a dropdown?
* how to display snap information if an update is available? version number and metadata can differ between locally installed snap and the latest from the store
I guess we can tackle the UI in a separate issue - the action buttons will just collapse into a column if there's not enough width for now.

feat: add refresh button to detail page

---

lib/constants.dart
lib/src/about/about_page.dart
lib/src/detail/detail_page.dart
lib/src/manage/manage_page.dart
lib/src/search/search_page.dart
lib/src/store/store_app.dart
lib/src/widgets/snap_card.dart
lib/src/widgets/snap_grid.dart
linux/my_application.cc

`kYaruPagePadding` (20) is not divisible by 8. This PR introduces a local `kPagePadding` (16) constant to make it easier to match things with a layout grid.
NOTE: `YaruBanner` has a hard-coded 4px margin around for the hover effect. This has been taken into account so that the visual spacing between cards becomes 16px.

feat: tweak paddings & geometries

---

lib/src/search/search_field.dart

_Originally posted by @Feichtmeier in https://github.com/ubuntu/app-store/issues/1287#issuecomment-1644088825_
((( the search field content padding now makes the icon and the text to be not in one line anymore
I guess either change the content padding or decrease icon and text size
)))
| | |
|---|---|
| ![image](https://github.com/ubuntu/app-store/assets/140617/192b7498-b6e9-4069-9899-44bd0d5277b2) | ![image](https://github.com/ubuntu/app-store/assets/140617/c1d7d5a3-2628-419b-93fa-dab2af4d5a31) |

fix(search): reduce icon size

---

lib/constants.dart
lib/src/widgets/snap_card.dart
lib/src/widgets/snap_grid.dart
lib/src/widgets/snap_icon.dart
lib/src/widgets/snap_title.dart

UDENG-1048
Intermediate widths between 800 and 1280 look a bit empty - I'll see if the medium sized cards work better there next week (and maybe a single column for narrow widths).
A weird issue that puzzled me for a bit: even though the minimum window size is set to 800x600 in the GTK app, the window can be resized down to 748x548 - is there an explanation for that difference?
|resolution|screenshot|
|-|-|
|800x600|![Screenshot from 2023-07-21 17-32-22](https://github.com/ubuntu/app-store/assets/113362648/df152b0f-093f-4e7e-a1d3-2ad7a19b22b2)|
|1280x800|![Screenshot from 2023-07-21 17-33-07](https://github.com/ubuntu/app-store/assets/113362648/3c2f4508-c2ef-4643-8b17-17ddfc0078be)|
|1680x1024|![Screenshot from 2023-07-21 17-34-01](https://github.com/ubuntu/app-store/assets/113362648/5d25c …

feat: implement responsive grid with fixed card sizes

---

lib/src/detail/detail_page.dart
lib/src/snapd/snap_model.dart

Adds a provider that returns a stream of the total progress values for a list of change IDs

feat: add progressProvider

---

lib/src/snapd/snap_model.dart

Waits for `getStoreSnap` to emit at least one event before building the detail page

fix(detail): ensure either local or store snap is available

---

lib/src/detail/detail_page.dart
lib/src/snapd/snap_model.dart
test/snap_model_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

Assumes that there is only a single active change, triggered by the user.

feat: add method to cancel ongoing change

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
test/detail_page_test.dart

UDENG-1048
Shows "Published" date as e.g. "Aug 4, 2023" or "4 Aug 2023", depending on the locale

feat: unify 'Published' labels, show abbr. month name

---

lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
lib/src/manage/manage_page.dart

UDENG-1048
Just a single item in the dropdown for the MVP
[Screencast from 2023-08-09 17-45-45.webm](https://github.com/ubuntu/app-store/assets/113362648/eedd543d-0acc-460e-bde2-a98c172cf515)

feat: add 'show details' action to manage page

---

lib/src/search/search_page.dart
lib/src/search/search_provider.dart
test/test_utils.dart

Preparation step to generalize the search page (links to a specific category on the explore page will open a general search page with an empty query and a pre-selected category filter).
Also: autodispose the search providers, as recommended [here](https://riverpod.dev/docs/concepts/modifiers/family#prefer-using-autodispose-when-the-parameter-is-not-constant).

feat: generalize search provider to support 'category'

---

lib/src/search/search_provider.dart

This seems to cause problems with the autocompletion - let's revert this for now and come back to it in case caching too many searches causes any issues in the future.

fix: don't autodispose search providers

---

lib/src/explore/explore_page.dart
lib/src/snapd/snap_category_enum.dart

Adds the accessibility-safe gradient colors for the banners from [here](https://github.com/ubuntu/app-store/discussions/1014#discussioncomment-4997933).

feat: import @Zoospora's banner gradients

---

lib/snapd.dart
lib/src/detail/detail_page.dart
lib/src/l10n/app_en.arb
lib/src/manage/manage_page.dart
lib/src/snapd/snap_l10n.dart
test/detail_page_test.dart
test/manage_page_test.dart
test/test_utils.dart

* Disable refresh button when an update is in progress
* Disable 'update all' button while checking for updates
* Show progress indicator in the 'update all' button during an update (similar to the primary action button on the detail page)

feat(manage): show progress in 'update all' button

---

linux/my_application.cc

Note that the gtk window currently needs to be 52px larger in both directions to account for the shadow from libhandy.

feat: set default window size to 1280x800

---

lib/src/detail/detail_page.dart
lib/src/manage/manage_page.dart

Thanks to @gerwitz for spotting this! Clicking on the '...' dropdown buttons containing the secondary actions on the manage and app pages only works once.
Turns out [this](https://github.com/ubuntu/app-store/pull/1322#discussion_r1289682273) doesn't actually work, since the `YaruOptionButton` doesn't get rebuild when the controller state changes, so we have to pass a closure that explicitly checks the controller state.

fix: dropdown button only works once

---

lib/src/explore/explore_page.dart
lib/src/explore/explore_provider.dart
lib/src/l10n/app_en.arb
lib/src/snapd/snap_category_enum.dart

Final explore page updates with temporary workarounds, since we don't have any data for "What's new", "Top rated", and "Recently updated" yet. Instead we just show six snaps from a given category below the respective banners.
[Screencast from 2023-08-18 14-31-43.webm](https://github.com/ubuntu/app-store/assets/113362648/14e80a8a-0d2d-423e-9b8c-796e14968d15)

feat: update explore page

---

lib/src/packagekit/packagekit_service.dart
test/packagekit_service_test.dart

Forgot to actually commit the changes for #1369 :D

feat: add clarifying comments, clean up tests

---

lib/appstream.dart
lib/main.dart
lib/snapd.dart
lib/src/appstream/appstream_search.dart
lib/src/appstream/appstream_service.dart
lib/src/explore/explore_page.dart
lib/src/l10n/app_en.arb
lib/src/search/search_field.dart
lib/src/search/search_page.dart
lib/src/search/search_provider.dart
lib/src/snapd/snap_search.dart
lib/src/store/store_app.dart
pubspec.yaml
test/appstream_service_test.dart
test/search_field_test.dart
test/search_page_test.dart
test/test_utils.dart

UDENG-1364
Ref #1367
@tim-hm when running this in debug mode loading the appstream metadata slows down the app drastically to the point where the UI becomes unresponsive for a short time. This should be hardly noticeable in release mode, though. However, there's some delay before the appstream autocompletion results become available - we should cache the metadata pool in a format that can be loaded more quickly later on.
I had to refactor the search providers a bit:
* src/search now only contains the common search logic (i.e. the search query and the autocompletion provider
* src/appstream and src/snapd now have their own separate search providers - there's no common filtering and sorting logic yet.

feat: add appstream results to autocompletion

---

lib/detail.dart
lib/snapd.dart
lib/src/about/about_page.dart
lib/src/detail/detail_page.dart
lib/src/explore/explore_page.dart
lib/src/l10n/app_en.arb
lib/src/manage/manage_page.dart
lib/src/search/search_field.dart
lib/src/search/search_page.dart
lib/src/snapd/snap_page.dart
lib/src/store/store_app.dart
lib/src/store/store_navigator.dart
lib/src/store/store_providers.dart
lib/src/store/store_routes.dart
lib/src/widgets/app_icon.dart
lib/src/widgets/snap_card.dart
lib/widgets.dart
test/initial_route_test.dart
test/snap_page_test.dart
test/store_navigator_test.dart
test/store_routes_test.dart

`SnapIcon` is already general enough that it can simply be renamed to `AppIcon` and later reused for debs.
Rather than trying to generalize the existing `DetailPage` with the current time constraints, I'd prefer moving and renaming it to `SnapPage` and add a separate `DebPage` later.

refactor: rename and move SnapIcon and DetailPage

---

lib/main.dart
lib/src/appstream/appstream_service.dart
lib/src/appstream/logger.dart

UDENG-1439
Fix #1397
* Loads l10n strings when instantiating the `AppstreamService`
* Defaults to "en" if the user's locale isn't supported

fix(appstream): add fallback locale

---

lib/snapd.dart
lib/src/manage/manage_page.dart
lib/src/snapd/logger.dart
lib/src/snapd/snap_model.dart
lib/src/snapd/snap_page.dart
lib/src/snapd/updates_model.dart
lib/src/store/store_app.dart
lib/src/widgets/dialogs.dart
lib/widgets.dart
test/manage_page_test.dart
test/snap_model_test.dart
test/snap_page_test.dart
test/test_utils.dart
test/test_utils.mocks.dart
test/updates_model_test.dart

UDENG-1363
UDENG-1422
Close #1366
Ref #1394 
(This state isn't reachable in practice, since we don't show the update button unless there is an update available)
* Adds a rudimentary error dialog widget
* Adds error streams to `SnapModel` and `UpdateModel`
* Logs snapd exceptions caught in the `SnapdModel` and `UpdateModel`
* Shows an error dialog on the `SnapPage` and `ManagePage` when errors are caught in the underlying models

feat: snapd error handling

---

lib/src/appstream/appstream_service.dart

UDENG-1440
Fix #1305
The stemming algorithm used in the appstream search function tends to turn 'y' into 'i' at the end of the word for some English words (can be tested [here](https://snowballstem.org/demo.html)).
I'm not sure what the best solution is, but simply keeping the original search tokens along with the ones generated by the stemmer seems to work well.
I couldn't reproduce the issue with `appstreamcli` so I had a brief look at appstream's implementation of the search logic, but didn't spot any obvious differences.

feat(appstream): keep original search tokens

---

lib/src/deb/deb_model.dart
lib/src/deb/deb_page.dart
lib/src/packagekit/logger.dart
lib/src/packagekit/packagekit_service.dart
test/deb_model_test.dart
test/deb_page_test.dart
test/packagekit_service_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

UDENG-1365
Fixes #1368
To keep things simple, I implemented the `errorStream` already in the service layer instead of throwing custom exceptions from there.

feat: packagekit error handling

---

lib/src/snapd/snap_page.dart

Closes #1392 
- I found it difficult to manage the splash filling only half the decorator box the thumbs lived in, so split them into two, one for up vote, one for down, and managed the splash in separate InkWells.
- Updated colors of thumbs and widget border to better align with the rest of the App Center & designs

fix: splash on up/down vote fills container

---

lib/main.dart
lib/src/ratings/ratings_model.dart
lib/src/ratings/ratings_service.dart
pubspec.yaml
test/ratings_model_test.dart
test/ratings_service_test.dart
test/snap_page_test.dart
test/test_utils.dart
test/test_utils.mocks.dart

Adds some unit tests for the communication with the ratings backend and the view model.

test: ratings service and model

---

CONTRIBUTING.md
README.md
pubspec.yaml

I've used the [templates](https://github.com/canonical/desktop-engineering/tree/main/project-repo/templates/common) as a starting point, but left out some things regarding bug reporting as there are still some things to figure out:
* Do we plan to track any issues on launchpad and use `ubuntu-bug`?
* Based on the previous question, we should also create different templates for bug reports and feature requests

docs: update README and add CONTRIBUTING.md

---

README.md

Adds a translation status badge to the README to increase the visibility of the project on weblate

docs: add weblate to readme

---

lib/src/snapd/updates_model.dart
test/updates_model_test.dart

Turns out the `refresh()` method wasn't handling snapd errors.
There will be an error dialog instead of an empty button now, in case snapd can't get the list of pending updates.
Fix #1429

fix(updates_model): handle error on refresh

---

.github/workflows/ci.yaml
.github/workflows/integration-test.yaml
.tool-versions
CONTRIBUTING.md
pubspec.yaml
snap/snapcraft.yaml

See https://github.com/canonical/ubuntu-desktop-provision/pull/179

feat: bump yaru and flutter versions

---

lib/src/packagekit/packagekit_service.dart
test/packagekit_service_test.dart
test/test_utils.mocks.dart

Fix #1485
- reads the local architecture from the snap environment (or from the output of `dpkg --print-architecture`)
- makes sure `resolve()` only returns packages with matching architecture
Adding proper support for foreign architectures requires a bit more care and some UI/UX input - I'd leave that as a separate issue.

fix(packagekit): check arch compatibility in resolve

---

packages/app_center/lib/src/about/about_page.dart

In this PR:
- Refactor an `ErrorWidget` to a `Text` widget when the app-center can't communicate with Github; the `ErrorWidget` was breaking the UIs with no possibility to see the rest of the content after the contributors.
fix #1506 
Before:
After:

fix: ErrorWidget breaking the about page UI.

---

packages/app_center/lib/src/l10n/app_en.arb

In this PR:
- Adding plural for l10n.
fix #1451 
Ex:
Now:
Before:

fix: plural spelling issue for l10n

---

packages/app_center/lib/src/snapd/snap_page.dart

In this PR:
- The snap page description often contains a link about the said snap, until now, the links were clickable but didn't do anything. Now, they open the link URL.
fix #1510

fix: link not usable on snap page description

---

snap/snapcraft.yaml

This ensures all local package dependencies are correctly set up before building the binary.
Should resolve the recent build failures on launchpad :crossed_fingers:

feat(snap): use melos in snapcraft.yaml

---

packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/lib/src/store/store_app.dart

In this PR:
- Adding a visual indicator (snackbar) when copying a link through the share button on the snap page.
fix #1462 
[Screencast from 2023-12-11 16-16-07.webm](https://github.com/ubuntu/app-center/assets/20175372/52963295-d806-422e-b590-e3d5673a983a)

feat: adding a snackbar for feedback on the share button

---

packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/src/store/store_app.dart
packages/app_center/pubspec.yaml

Currently, the window in the Activities view in Gnome Shell has "snap-store" as its name, which is incorrect because this is the brand-new "App Center". The reason is that the Activities view shows the window title, but the app center doesn't set it, so it is set to the binary name.
The patch uses the translations from the .desktop file, thus it doesn't require extra effort to ensure that the name shown in the Activities view is correctly translated.
fix #1425

Show "App Center" in Gnome Shell activities view

---

packages/app_center/lib/src/explore/explore_page.dart
packages/app_center/lib/src/store/store_app.dart
packages/app_center/lib/src/store/store_pages.dart

In this PR:
- Open the correct section when clicking on a banner button from the explore page.
fix #1379

fix: sidebar navigation highlight

---

packages/app_center/assets/app-center.desktop

[snap]: fix hardcoded app icon

---

packages/app_center/lib/constants.dart
packages/app_center/lib/src/deb/deb_page.dart
packages/app_center/lib/src/manage/manage_page.dart
packages/app_center/lib/src/snapd/snap_page.dart

fixes #1502 by setting standard height for Circular progress indicator, which will not make update button jump out of its height.

fix: set standard height for Circular progress indicator everywhere.

---

packages/app_center/lib/src/search/search_page.dart
packages/app_center/pubspec.yaml

In this PR:
- Using the new parameter `expanded` from the `MenuButtonBuilder` to follow implementation of canonical/ubuntu-flutter-plugins#372

fix: using the new parameter for the MenuButtonBuilder

---

packages/app_center/lib/src/snapd/snap_page.dart

snap_page: use mouse hand instead of pointer for voting icons

---

packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/lib/src/snapd/snap_report.dart
packages/app_center/pubspec.yaml

In this PR:
- Adding the UI and the necessary functionality to be able to report a Snap. It use the same principle as snapcraft.io
There was no Figma file, so I improvised some visual aspects to be as close as possible from snapcraft.io, but with Yaru theming.
fix #1490

feat: adding the report feature for snaps

---

.github/workflows/snap.yaml

The asdf and melos actions shouldn't be here, as they pollute the snapcraft environment, which caused the recent snap job failures.

fix: remove asdf and melos-action from snap workflow

---

.gitignore
codecov.yaml
melos.yaml

* Removes generated protobuf files from coverage in `melos coverage:cleanup`
* Removes unneeded `ignore` rule in codecov.yaml
* Removes generated files from `melos format` for consistency

chore: remove generated files from coverage

---

packages/app_center/lib/src/manage/manage_page.dart

> One thing to amend is that the cancel button should be hidden until the 'Update all' is trigged, as it can be misleading for the users to have a cancel button without context.
As per the comments form #1536, this PR will hide cancel button when updates are not in progress.

fix: Manage page: Hide cancel button when updates are not in progress.

---

packages/app_center/lib/src/search/search_field.dart
packages/app_center/lib/src/store/store_app.dart
packages/app_center/test/search_field_test.dart

This pull request adds a keyboard shortcut to focus the search text field by clicking ctrl+f
For some reason the formatting (indenting) destroys the diff look. And kind of makes sense because I made the `YaruTheme` a child of the `CallbackShortcuts`. Is there a formatting helper or a guide for this? I could push directly to this branch to fix these code formatting issues if needed
Also, unit tests are failing because I changed the SearchField constructor signature so I have to rewrite the unit tests for them to succeed. I can do that in a separate commit if you're ok with it.

feat: ctrl+f shortcut to focus search field

---

packages/app_center/test/snapd_cache_test.mocks.dart
packages/app_center/test/snapd_watcher_test.mocks.dart
packages/app_center/test/test_utils.mocks.dart

`package:snapd/snapd.dart` added more options to the find method
Regenerating mocks added these lines
Is this the right way to regenerate mocks on the main branch? Via PR?

tests: regenerate snapd mocks

---

packages/app_center/lib/src/manage/manage_page.dart
packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/lib/src/store/store_pages.dart

The borders are sometimes 2 sometimes 1 pixel thick.
In yaru.dart we unified this to 1.
This unifies the dividers in the store app to 1.
This is mostly visible on the manage page.
Before:
After:

fix: unify divider thickness

---

packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/test/snap_page_test.dart

In my previous PR, I added a new entry in the `snapInfoBar`, that was `version`. But, I showed it from `snap.version`, which didn't update when the channel is changed. So, changed the version to `channel.version`. Sorry for the previous inconvenience. 
EDIT: for local snaps, the channels doesn't exit which fails the test. So, if `channelInfo.version` doesn't exist, fallbacking to `snap.version`.

snap_page: version not updated based on channel

---

melos.yaml
snap/snapcraft.yaml

Sorry for the noise, seems like disabling parallel `pub get`s doesn't realiably fix the [build issues](https://launchpad.net/~desktop-snappers/+snap/app-center/+build/2396810). This reintroduces the `set +/-e` commands (removed in #1519) to ignore the potential stack overflow during `pub get`.

fix(snapcraft): revert to original fix ignoring pub errors

---

.tool-versions
melos.yaml
packages/app_center/integration_test/app_center_test.dart
packages/app_center/lib/main.dart
packages/app_center/lib/src/about/about_page.dart
packages/app_center/lib/src/deb/deb_page.dart
packages/app_center/lib/src/explore/explore_page.dart
packages/app_center/lib/src/games/games_page_external_tools.dart
packages/app_center/lib/src/games/games_page_featured.dart
packages/app_center/lib/src/manage/manage_page.dart
packages/app_center/lib/src/search/search_field.dart
packages/app_center/lib/src/search/search_page.dart
packages/app_center/lib/src/snapd/snap_category_enum.dart
packages/app_center/lib/src/snapd/snap_page.dart
packages/app_center/lib/src/snapd/snap_report.dart
packages/app_center/lib/src/store/store_app.dart
packages/app_center/lib/src/store/store_pages.dart
packages/app_center/lib/src/widgets/app_card.dart
packages/app_center/lib/src/widgets/app_icon.dart
packages/app_center/lib/src/widgets/dialogs.dart
packages/app_center/lib/src/widgets/screenshot_gallery.dart
packages/app_center/pubspec.yaml
packages/app_center/test/manage_page_test.dart
packages/app_center/test/snap_page_test.dart
packages/app_center/test/store_app_test.dart
snap/snapcraft.yaml

- for yaru yaru test and ubuntu widgets needed an update
- for which flutter  and file needed to be updated
- additionally updated handy_window to align gtk theme with yaru.dart
@BLKKKBVSIK 
looked for the workflow files, but apparently didnt find where you set up the flutter version? in some other repo/script?

chore: update flutter, yaru, handy_window

---

CONTRIBUTING.md
README.md

It looks like that app-center is now under ubuntu-desktop-translations.
/cc @Feichtmeier @d-loose

docs: Fix Weblate link

---

packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/src/manage/manage_l10n.dart
packages/app_center/lib/src/manage/manage_page.dart

Hi there ✌️ I'm a huge fan of the new app center. Thank you very much for developing. Maybe I can contribute a little bit?
The time since the last update
is only displayed in days right
now, while it could be nice
to also have it in months and
years.
I was not sure where to put the logic for the formatted string
calculation. If you know a
better place like a /utils directory
that I might have overseen,
please ping me and I will
change it.

chore: Format time since last update as days, months or years

---

packages/app_center/lib/config.dart
packages/app_center/lib/main.dart
packages/app_center/test/config_service_test.dart
packages/app_center_ratings_client/lib/src/ratings_client.dart
snap/snapcraft.yaml

`ratings.ubuntu.com` now serves gRPC over TLS. This PR adds the necessary configuration options that can be set via the environment and provides the corresponding values in the snapcraft.yaml.

feat: connect to ratings service via TLS

---

snap/snapcraft.yaml

According to the snapcraft.yaml reference:
> `apps.<app-name>.refresh-mode`
> Controls whether the daemon should be restarted during a snap refresh.
> Type: string
> Requires daemon to be set in app metadata. Can be one of the following:
> endure, restart, or ignore-running (defaults to restart)
So it seems like we can't use this for a desktop app. In the meantime we've already merged #1663 as a fix for #1643.
This reverts commit 80e36895890f1357e216bdb676024b09b636a9f5.

fix(snapcraft): remove `refresh-mode`

---

packages/app_center/lib/error/error.dart
packages/app_center/lib/error/error_observer.dart
packages/app_center/lib/main.dart

Adds a `ProviderObserver` that logs provider build errors. This mostly concerns exceptions thrown due to connection errors (ratings backend or snapd unavailable), but potentially other errors we're not aware of that might be useful for debugging.

feat: add ErrorObserver

---

packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/games/games_page_external_tools.dart
packages/app_center/lib/search/search_page.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/lib/store/store_app.dart
packages/app_center/lib/store/store_observer.dart

This moves up the back button to the title bar.
Supersedes: #1664
Fixes: #1727
Follow up: Move flag and share icons to be at the same height as the title

fix: Move back button to the title bar

---

packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/snapd/snap_page.dart

fix: Move share+flag icons to title row

---

packages/app_center/lib/constants.dart
packages/app_center/lib/explore/explore_page.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/search/search_field.dart

|                                                   | before| after| 
| ---| ---| ---| 
| explore page category button borderradius |<img width="226" alt="grafik" src="https://github.com/ubuntu/app-center/assets/15329494/30da2412-6094-4c52-834b-7dbfb5e1141c">|<img width="226" alt="grafik" src="https://github.com/ubuntu/app-center/assets/15329494/91092383-a165-4b32-b492-773f29279928">| 
|manage page open button padding               |<img width="120" alt="grafik" src="https://github.com/ubuntu/app-center/assets/15329494/656be384-5de2-4006-b466-7c1ae9ed947a">|<img width="132" alt="grafik" src="https://github.com/ubuntu/app-center/assets/15329494/d0959d90-b086-403a-9875-6cd32bd8258e">|
|search field alignment                                    |<img width="910" alt="grafik" …

fix: styling improvements

---

packages/app_center/lib/store/store_app.dart
packages/app_center/lib/store/store_providers.dart
packages/app_center/test/initial_route_test.dart

Adds an `--updates` flag that can be used to immediately show the manage page when the app is launched.
The way App Center currently manages routes and pages is a bit messy, so this would place the manage page on top of the navigator stack in the right pane, instead of making it the initial selection in the menu on the left side. See screenshots for more details.
To make this work properly, we'd need to refactor the store navigation and routes quite a bit.
|Proper implementation|Quick implementation (this PR)|
|-|-|
|![Screenshot from 2024-07-09 18-01-29](https://github.com/ubuntu/app-center/assets/113362648/8ac7aa12-43ee-405a-aa3e-24a3ac2bd6c4)|![Screenshot from 2024-07-09 18-01-22](https://github.com/ubuntu/app-center/assets/113362648/02442d5d-6506-425a-863a-6bfbb63e9400)|
Ref #1733 …

feat: add --updates flag to open manage page

---

packages/app_center/assets/app-center-updates.desktop
snap/snapcraft.yaml

This patch adds an extra, invisible, .desktop file that opens the store in the "updates" page directly. This is needed because in the new Refresh App Awareness, we want to allow the user to open the snap-center in the "updates" page directly from a "pending update" notification, but since it is `snapd-desktop-integration` the application that opens it, and it is inside another snap, the only way that it has to launch the `snap-center` is using the `desktop-launch` DBus interface. This interface, unfortunately, doesn't allow to pass parameters, only allows to pass the name of a `.desktop` file to launch, so this workaround is needed.

Add launcher for "updates"

---

packages/app_center/lib/layout.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/test/manage_page_test.dart

[Screencast from 2024-07-25 15-33-20.webm](https://github.com/user-attachments/assets/4407889d-1319-45b0-9206-1f363a3b1a72)
Also fixed so that the height doesn't change when the loaded switches to the text, which looked kind of janky.
Closes: #1752

fix: Avoid double loader for updates available section

---

packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/deb/local_deb_page.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/lib/widgets/app_info_bar.dart
packages/app_center/lib/widgets/placeholders.dart
packages/app_center/lib/widgets/shimmer_placeholder.dart

In this PR:
- Adding shimmers placeholder text during the loading of the ratings.
fix #1447
[Screencast from 2023-12-12 11-54-14.webm](https://github.com/ubuntu/app-center/assets/20175372/6d7ee919-6cde-4d8f-b055-df909c400d64)

feat: adding shimmer when the ratings are loading.

---

scripts/install-fvm.sh

Fixes launchpad build failures for arm64. See https://github.com/leoafarias/fvm/pull/747

fix: add aarch64 arch to fvm install script

---

packages/app_center/lib/search/search_field.dart

The search bar should automatically focused when 'clear search text' button is clicked. This is small tweak but usefull too. I do search, do some activities. Then search bar become unfocused. Then I click on clear search button and start typing my query, And then I see that Search bar is not focused. I have to manually click on the textfeild to focus it. This pull request will automatically focus search bar when someone click on clear search button. I made this changes from my experience.

fix: SearchBar autofocus when click on clear btn

---

packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/snapd/snap_page.dart

fix: Remove secondary action icons

---

packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/widgets/snap_menu_item.dart

These `_ButtonBarForUpdate` and `_ButtonBarForOpen` should probably be generalized at some point, but I think that can be done later since it's only two of them now.
Closes: #1775

fix: Align extra snap menus

---

snap/snapcraft.yaml

this pull request migrates the app center to core24
migration seems very straightforward only requiring the change in the base parameter and adding git as build parameter (how did it get it before by the way?)

snap: update to core24

---

SECURITY.md

Quoting SEC0026 - SSDLC
> SECURITY.md (V1.1)
> Any public repository must also include a SECURITY.md file in the root directory, which educates users/contributors on
> how to report a security concern.
The content of the file is based on the template referenced in the spec and what other Canonical repository are already using

docs: Add instructions on how to report security issues

---

packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/manage/update_button.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/test/manage_page_test.dart

Use the `UpdateButton` from the manage page on the snap page too so that we get info like "Quit to update"
Fixes: #1773

fix: Use `UpdateButton` on SnapPage

---

packages/app_center/lib/manage/local_snap_providers.dart
packages/app_center/lib/manage/updates_model.dart
packages/app_center/lib/snapd/snap_model.dart

fix: Don't reload lists after each update in `refreshAll`

---

packages/app_center/lib/snapd/snap_page.dart

Instead of putting using the overflow bar we'll make the switch button flexible so that it can shrink when it needs to (and be larger when the text is long).
Fixes: #1513

fix: Accommodate long switch channel buttons texts

---

packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/manage/manage_snap_tile.dart

Fixed a bug reported on Discord where the length of the text makes the button bar overflow:
(Image of how the bug looks like, not how it looks like after the fix)

fix: Use `IntrinsicWidth` for rows with space

---

packages/app_center/build.yaml
packages/app_center/lib/ratings/ratings_data.dart
packages/app_center/lib/ratings/ratings_model.dart
packages/app_center/lib/snapd/cache_file.dart
packages/app_center/pubspec.yaml
packages/app_center_ratings_client/build.yaml
packages/app_center_ratings_client/lib/src/ratings.dart
packages/app_center_ratings_client/lib/src/ratings.freezed.dart
packages/app_center_ratings_client/pubspec.yaml

feat: cache snap ratings for 24 hours

---

melos.yaml
packages/app_center/integration_test/app_center_test.dart
packages/app_center/lib/constants.dart
packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/deb/local_deb_page.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/manage/manage_snap_tile.dart
packages/app_center/lib/manage/snap_actions_button.dart
packages/app_center/lib/manage/update_button.dart
packages/app_center/lib/snapd/snap_model.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/lib/widgets/active_change_content.dart
packages/app_center/pubspec.yaml
packages/app_center/test/manage_page_test.dart
packages/app_center/test/snap_page_test.dart
packages/app_center/test/test_utils.dart
packages/app_center_ratings_client/pubspec.yaml

[Screencast from 2024-10-14 10-50-44.webm](https://github.com/user-attachments/assets/044feebf-f5a1-4e7a-83dd-3c1820190361)
* Alignment of some context menues are still a bit off when it has extra space.
* We shouldn't merge this until a new yaru version is released.

feat: Unify update/install/open and use YaruSplitButton

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Adds issue templates for bug reports and enhancement.
You can preview what these options look like on my branch [here](https://github.com/matthew-hagemann/app-center/issues/new/choose)

 Feat: add issue templates

---

packages/app_center/lib/constants.dart
packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/deb/local_deb_page.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/test/manage_page_test.dart

Adds links to https://documentation.ubuntu.com/server/tutorial/managing-software/#installing-deb-packages to the 'Manage' and debian package pages ([figma](https://www.figma.com/design/c4noYODoMPFNn04gsJVJLE/App-Center?node-id=1860-4258&t=siVMXxKcEuzG0RHB-1))
UDENG-3383

feat: add deb management links

---

packages/app_center/lib/games/games_page.dart
packages/app_center/lib/games/games_page_featured.dart
packages/app_center/lib/ratings/rated_category_model.dart
packages/app_center/lib/ratings/rated_category_model.g.dart
packages/app_center/lib/ratings/ratings_service.dart
packages/app_center/lib/snapd/snapd_service.dart
packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/widgets/app_card.dart
packages/app_center/lib/widgets/category_snap_list.dart
packages/app_center/lib/widgets/small_banner.dart
packages/app_center/lib/widgets/snap_grid.dart
packages/app_center/test/ratings_service_test.dart
packages/app_center/test/test_utils.dart
packages/app_center_ratings_client/lib/app_center_ratings_client.dart
packages/app_center_ratings_client/lib/src/generated/ratings_features_chart.pb.dart
packages/app_center_ratings_client/lib/src/generated/ratings_features_chart.pbenum.dart
packages/app_center_ratings_client/lib/src/generated/ratings_features_chart.pbgrpc.dart
packages/app_center_ratings_client/lib/src/generated/ratings_features_chart.pbjson.dart
packages/app_center_ratings_client/lib/src/ratings_client.dart
packages/app_center_ratings_client/protos/ratings_features_chart.proto
packages/app_center_ratings_client/test/ratings_client_test.dart
snap/snapcraft.yaml

This PR adds an ordered list of snaps based on their rating to the Games tab. Doing this required adding support for the top charts endpoints from the ratings service to the ratings client.
I've added this as a new variation of the `CategorySnapList`, so hopefully if we intend to incorporate top charts into other areas of the app, we can easily reuse the `RatedCategorySnapList`. A spinner is displayed while the list is loading; it does take a moment since we have to fetch the snap details for each snap ID.
This is more or less what it looks like, though the actual snaps displayed will not be the same:
UDENG-3351

feat: Add rated category snaps to the Games tab

---

packages/app_center/lib/snapd/cache_file.dart

Old cache data for the ratings will be missing the snap_name field. If that's the case we should ignore the error and throw away the cache data.
UDENG-5771

feat: ignore outdated ratings cache

---

.github/workflows/ci.yaml

Runs the TICS github action on pushes to `main`
UDENG-5819

ci: add tics action

---

.github/workflows/ci.yaml

Somehow the tics job assumes "master" as the branch name (see [here](https://github.com/ubuntu/app-center/actions/runs/12884578321/job/35922462758)), although we're using "main". According to the [docs](https://github.com/marketplace/actions/tics-code-quality-analysis#advanced-parameters) we can provide a `branchname` (all lowercase) parameter - let's see if that helps.
UDENG-5819

fix: add `branchname` to tics job

---

packages/app_center/lib/src/l10n/app_en.arb

Removes an unused l10n string introduced in #1751. Someone asked for more context when translating it on weblate, when I realized we're not actually using it anywhere.

chore: remove unused l10n string

---

.github/workflows/ci.yaml
melos.yaml

This seems to work correctly now :)
The TiCS backend searches for coverage files in the `coverage` directory in the repository root. It seems like it actually only reads the lcov files, so the conversion to cobertura XML is unnecessary (for Dart code). Since the file paths in the coverage output are relative, they need to be adjusted when moving the output files around, so I'm just turning them into absolute paths.
I've also added a "cleanup" step, since symlinks in `.fvm` and `packages/*/linux/flutter/ephemeral` that point to directories outside of the repository, seem to cause problems with TiCS.
UDENG-5819

ci: reenable tics action

---

packages/app_center/lib/widgets/app_card.dart

Removes the background color for app cards.
|--------|-------|
| ![image](https://github.com/user-attachments/assets/21663416-9952-44db-a161-9e8ac9243d18) | ![image](https://github.com/user-attachments/assets/6a0c5515-bcd6-49f5-a098-4aa2cae81b56) |
Related to the issues described in https://github.com/ubuntu/app-center/pull/1818

fix: Remove card background color

---

packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/widgets/app_page_section.dart

Adds accessible labels to the share and report buttons on snap pages, as well as the labels for expand/collapse sections. These are not visual labels, just text read by the screen reader. For example, it will read "Report this snap push button" when the report button receives focus.
This also adds the missing "Link copied" snack bar that appears when copying the share link from the snap page to the deb page. I think this fits in the PR since it addresses feedback of the button.
---
Audit 1859619
UDENG-7136

fix(a11y): Add labels to page actions and expandable sections

---

packages/app_center/lib/src/l10n/app_en.arb
packages/app_center/lib/widgets/screenshot_gallery.dart

Adds semantic labels "Next image" and "Previous image" to the next and previous buttons on the screenshot gallery.
This also adds some bare-bones screen reader labels to gallery images (i.e. "image 1", "image 2", etc.). From commit https://github.com/ubuntu/app-center/pull/1927/commits/e54b63a77452bc56fbb0b4239b84fb9ef274bd1e:
> Note that this is effectively image alt text, and this alt text is almost useless.
> 
> To get real alt text, snapcraft.io would need to support alt text for images and make that text also available via their API.
This is still an improvement over the previous behavior where images were not announced by the screen reader *at all*.
---
Audit 1859635
Audit 1860733
Audit 1860783
UDENG-7137

fix(a11y): Add semantic labels to gallery buttons

---

packages/app_center/lib/snapd/snap_page.dart

The channel dropdown selector for snaps is read as the actual value of the dropdown, i.e. "latest/stable v1.5.517". This change makes it so the dropdown is read as "Channel push button".
Our audit suggests the behavior that is implemented by this PR, but I wonder if it would be useful for the version to still be read aloud. Or, perhaps just it being read when you click  it is sufficient (existing behavior of this PR).
This also fixes how the actual channel info is read in each dropdown entry. Before, it was read visual column by column, when it actually should be read by row.
Implementation wise, I had to manually define a `Semantics` label since screen readers will read the order of elements as they're defined. I don't think we have an option of reordering the widgets to fix the problem …

fix(a11y): Add corrected semantics to channel dropdown

---

.github/workflows/ci.yaml

This removes the 'cleanup' step for the tics action again. It was added previously to resolve issues related to the symlinks in `.fvm`. This directory has now been added to the ignored paths on the tiobe side. We need to keep the build artifacts around, so that Coverity can re-build the project and gather data from the compiler output.

ci(tics): remove cleanup step

---

packages/app_center/lib/store/store_pages.dart

Adds a focus ring to the left navigation. This ring will change if you use your keyboard to tab-navigate through it.
I encountered some issues with tab navigation while implementing this, so I think there's further work to investigate in Yaru and would probably simplify this change in the future. 
---
Audit 1862144
UDENG-6907
UDEAA-96

feat(a11y): Left Navigation focus ring

---

packages/app_center/lib/about/about_page.dart
packages/app_center/lib/constants.dart
packages/app_center/lib/deb/deb_page.dart
packages/app_center/lib/manage/manage_page.dart
packages/app_center/lib/snapd/snap_page.dart
packages/app_center/lib/snapd/snap_report.dart
packages/app_center/lib/widgets/hyperlink_text.dart

Makes all text hyperlinks able to be focused via the keyboard. Previously, hyperlinks were all styled slightly differently and were never able to be focused or activated by the keyboard alone. This PR changes that by adding a unified `HyperlinkText` widget for all instances of hyperlinks.
Design notes:
- All hyperlinks now use Vanilla's blue hyperlink color (theme dependent)
- Hyperlinks have focus rings with the same corner radius as Yaru buttons, with a width of 2
<details>
<summary>Screenshots</summary>
About page non-focused
About page focused
---
Snap page non-focused
Snap page focused
</details>
---
Audit 1860919
UDEAA-45

feat(a11y): Keyboard focusable hyperlinks

---

packages/app_center/lib/manage/manage_page.dart

When scrolling in the Manage page, the top and bottom padding was still there, even though these paddings should be present when at the very top/bottom of the page, as explained in the issue comments. 
The first commit was because I had made a fix 15 hours ago but it hadn't completely solved the issue. After following suggestions made in the issue comments, it seems to be okay now.
Closes #1955

fix: unnecessary paddings on manage page

---

packages/app_center/lib/snapd/snap_report.dart

Adds the label that accompanies inputs in the report dialog to be read when the input is focused.
---
UDENG-7570

fix(a11y): Report input semantics

---

packages/app_center/lib/widgets/banner.dart

Adds a visible focus state to banner apps when focused with the keyboard, matching the same grow+tooltip that the hover state invokes.
---
UDENG-7561
Audit 1850477

fix(a11y): Add visible focus state to banner apps
